### ISSUE TITLE
Is Varnish included?

### ISSUE THREAD

**Issue by lilbumblebear** [bitnami/bitnami-docker-magento#101]
I cannot find any documentation about whether this image will also install Varnish, like the Google Compute Engine Bitnami Magento image will?  Can you please confirm if Varnish is included?

**Comment by tompizmor** [comment]
Hello @lilbumblebear,

The Bitnami docker image for Magento does not include Varnish. You can take a look to the bitnami components included in the image in the [Dockerfile](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/Dockerfile#L6-L10)

**Comment by lilbumblebear** [comment]
Thank you @tompizmor!  I checked the Dockerfile yesterday, but am still new at reading them.  Thank you for the link!

**Comment by tompizmor** [comment]
The Cloud image ships everything Magento needs to run in the same server, such as the web server and the database server. Also, to improve the performance includes Varnish, also in the same server. 

In the container world, every service should be a different container. For example, you have one container for Magento and other for the database. For that reason, Varnish for Magento container should be configured as a different service in a different container.
