### ISSUE TITLE
magento does not start

### ISSUE THREAD

**Issue by onanim** [bitnami/bitnami-docker-magento#105]
```
magento_1  | nami    INFO  Initializing apache
magento_1  | apache  INFO  ==> Patching httpoxy...
magento_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/apache'
```

**Comment by javsalgar** [comment]
Hi,

Could you provide more information about your environment? Could you share the docker-compose file that you used to launch the instance?

**Comment by onanim** [comment]
I just follow TLDR; section without any changes
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

**Comment by onanim** [comment]
> Docker version 1.13.1, build 1185cfd/1.13.1

That is from Fedora 29

**Comment by javsalgar** [comment]
I think it has to do with SELinux being enabled and causing this kind of issues. 

More info here: https://nanxiao.me/en/selinux-cause-permission-denied-issue-in-using-docker/


Could you try using `setenforce 0` and try again?

**Comment by onanim** [comment]
Thanks, yes, works now
