### ISSUE TITLE
Any theme instaled in app/design/fontend doesn't work

### ISSUE THREAD

**Issue by gbitdev** [bitnami/bitnami-docker-magento#107]
Any theme installed in `/opt/bitmani/magento/htdocs/app/design/fontend` doesn't work.
Checked with all kinds permission and ownership.
They appear to choose them in configuration but:
1. Static files do not depoloy after `bin/magento setup:static-content:deploy -f ` 
2. Always generates same exeption 
<pre>1 exception(s):
Exception #0 (InvalidArgumentException): Required parameter 'theme_dir' was not passed
Exception #0 (InvalidArgumentException): Required parameter 'theme_dir' was not passed
#1 Magento\Framework\View\Design\Fallback\Rule\Theme->getPatternDirs(array('area' => 'frontend', 'locale' => 'pl_PL', 'file' => 'i18n/pl_PL.csv', 'theme_dir' => NULL)) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/Resolver/Simple.php:124]
#2 Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolveFile(&Magento\Framework\View\Design\Fallback\Rule\Theme#00000000797934d2000000005fa217d2#, 'i18n/pl_PL.csv', array('area' => 'frontend', 'theme' => &Magento\Theme\Model\Theme#00000000797934d0000000005fa217d2#, 'locale' => 'pl_PL', 'file' => 'i18n/pl_PL.csv')) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/Resolver/Simple.php:66]
#3 Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolve('locale', 'i18n/pl_PL.csv', 'frontend', &Magento\Theme\Model\Theme#00000000797934d0000000005fa217d2#, 'pl_PL', NULL) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/LocaleFile.php:42]
#4 Magento\Framework\View\Design\FileResolution\Fallback\LocaleFile->getFile('frontend', &Magento\Theme\Model\Theme#00000000797934d0000000005fa217d2#, 'pl_PL', 'i18n/pl_PL.csv') called at [vendor/magento/framework/View/FileSystem.php:106]
#5 Magento\Framework\View\FileSystem->getLocaleFileName('i18n/pl_PL.csv', array('area' => 'frontend', 'locale' => 'pl_PL', 'scope' => 'default', 'theme' => 'Gbitweb/crest-po...', 'module' => 'Magento_Cms', 'themeModel' => &Magento\Theme\Model\Theme#00000000797934d0000000005fa217d2#)) called at [vendor/magento/framework/Translate.php:410]
#6 Magento\Framework\Translate->getThemeTranslationFileName('pl_PL', array('area' => 'frontend', 'locale' => 'pl_PL', 'scope' => 'default', 'theme' => 'Gbitweb/crest-po...', 'module' => 'Magento_Cms')) called at [vendor/magento/framework/Translate.php:453]
#7 Magento\Framework\Translate->getThemeTranslationFilesList('pl_PL') called at [vendor/magento/framework/Translate.php:350]
#8 Magento\Framework\Translate->_loadThemeTranslation() called at [vendor/magento/framework/Translate.php:220]
#9 Magento\Framework\Translate->loadData('frontend', false) called at [vendor/magento/framework/App/Area.php:245]
#10 Magento\Framework\App\Area->_initTranslate() called at [vendor/magento/framework/App/Area.php:216]
#11 Magento\Framework\App\Area->_loadPart('translate') called at [vendor/magento/framework/App/Area.php:143]
#12 Magento\Framework\App\Area->load('translate') called at [vendor/magento/framework/View/DesignLoader.php:55]
#13 Magento\Framework\View\DesignLoader->load() called at [vendor/magento/framework/App/Action/Plugin/Design.php:48]
#14 Magento\Framework\App\Action\Plugin\Design->beforeDispatch(&Magento\Cms\Controller\Index\Index\Interceptor#0000000079793529000000005fa217d2#, &Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:121]
#15 Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:39]
#17 Magento\Cms\Controller\Index\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/App/FrontController.php:159]
#18 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#, &Magento\Cms\Controller\Index\Index\Interceptor#0000000079793529000000005fa217d2#) called at [vendor/magento/framework/App/FrontController.php:99]
#19 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#22 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000007979367f000000005fa217d2#, &Closure#000000007979367d000000005fa217d2#, &Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#24 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000007979367f000000005fa217d2#, &Closure#000000007979367d000000005fa217d2#, &Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000079793746000000005fa217d2#) called at [vendor/magento/framework/App/Http.php:136]
#28 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#29 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#30 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000007979371e000000005fa217d2#) called at [index.php:39]
</pre>

When they installed with composer everything is ok.

**Comment by tompizmor** [comment]
Did you check [this post](https://magento.stackexchange.com/questions/100011/required-parameter-theme-dir-was-not-passed) from StackOverflow?

It seems that error occurs when you have configured a theme that does not exist on the file system.

Can you point us to a free theme we can use to debug the issue on our side?

**Comment by gbitdev** [comment]
Hello.
Yes I know this post from statckoverflow - that's why at the beginning I thought this is problem with permissions. 
Based on [this article](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html) i created simplest [theme](https://gitlab.com/gbitdev/magento2-theme-blank/).
It is working on bare metal and [alex cheng](https://github.com/alexcheng1982/docker-magento2) docker  install but not on bitmani one.

**Comment by tompizmor** [comment]
Hi @gbitdev,

I cloned your theme inside `/opt/bitmani/magento/htdocs/app/design/fontend/gbitdev`, run `bin/magento setup:static-content:deploy -f` and I didn't get any error:

```
root@6696e468bd88:/opt/bitnami/magento/htdocs# bin/magento setup:static-content:deploy -f

Deploy using quick strategy
frontend/Magento/blank/en_US            2245/2245           ============================ 100% %  2 secs
adminhtml/Magento/backend/en_US         2328/2328           ============================ 100% %  1 sec
frontend/Magento/luma/en_US             2260/2260           ============================ 100% %  2 secs

Execution time: 11.765933036804
```

However,  I didn't see any new theme in the admin panel list:

<img width="1019" alt="Screenshot 2019-05-06 at 13 37 03" src="https://user-images.githubusercontent.com/4026184/57222775-1b32b980-7004-11e9-8bff-dd0a091006a2.png">

Do you know if I am missing something in order to reproduce the issue? I have checked that Magento is in developer mode too.

**Comment by gbitdev** [comment]
Hi @tompizmor,
I tried this too just now and you are right - I do not see it in admin panel too.
But, this is something what's shouldn't happend too - this basic theme works "normally" (shows in admin panel and do not causes any error) on bare installation or with mentioned ealrier alex cheng docker image.
I will try to find how  reproduce error tomorow.

**Comment by tompizmor** [comment]
I was able to reproduce it mounting the theme folder using a local volume in this way:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    image: 'bitnami/magento:2'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_HOST=MY_HOSTNAME
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
      - './themes:/opt/bitnami/magento/htdocs/app/design/frontend'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```

The content of the local _themes_ folder is:

```
└── themes
    └── gbitdev
        └── magento2-theme-blank
            ├── composer.json
            ├── media
            │   └── preview.jpg
            ├── registration.php
            └── theme.xml
```

And as you can see, the theme is listed now in the admin panel:

<img width="1320" alt="Screenshot 2019-05-07 at 10 02 54" src="https://user-images.githubusercontent.com/4026184/57283568-be8cd880-70af-11e9-87a3-e980d19ed0ea.png">

Once I enable it, I get the same issue you reported:

```
1 exception(s):
Exception #0 (InvalidArgumentException): Required parameter 'theme_dir' was not passed

Exception #0 (InvalidArgumentException): Required parameter 'theme_dir' was not passed
<pre>#1 Magento\Framework\View\Design\Fallback\Rule\Theme->getPatternDirs(array('area' => 'frontend', 'locale' => 'en_US', 'file' => 'i18n/en_US.csv', 'theme_dir' => NULL)) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/Resolver/Simple.php:124]
#2 Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolveFile(&Magento\Framework\View\Design\Fallback\Rule\Theme#0000000071ec7a980000000051aa6453#, 'i18n/en_US.csv', array('area' => 'frontend', 'theme' => &Magento\Theme\Model\Theme#0000000071ec7aa50000000051aa6453#, 'locale' => 'en_US', 'file' => 'i18n/en_US.csv')) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/Resolver/Simple.php:66]
#3 Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolve('locale', 'i18n/en_US.csv', 'frontend', &Magento\Theme\Model\Theme#0000000071ec7aa50000000051aa6453#, 'en_US', NULL) called at [vendor/magento/framework/View/Design/FileResolution/Fallback/LocaleFile.php:42]
#4 Magento\Framework\View\Design\FileResolution\Fallback\LocaleFile->getFile('frontend', &Magento\Theme\Model\Theme#0000000071ec7aa50000000051aa6453#, 'en_US', 'i18n/en_US.csv') called at [vendor/magento/framework/View/FileSystem.php:106]
...
```

We will further investigate the issue and let you know once we have more information.

**Comment by bkmagnetron** [comment]
I'm also facing similar kind of issue for custom module under `app/code`

**Comment by tompizmor** [comment]
Hi @bkmagnetron,

In order to support both upgrades and persistence, the Bitnami Magento image does some symlinks from the installation directory (`/opt/bitnami/magento`) to the persistence directory (`/bitnami/magento`).

I think that symlinks might be causing this kind of issues but we would have to verify to be sure. 
We already had similar issues with other apps like PrestaShop and at the end, we decide to persist the whole installation directory. The drawback of doing this is that upgrades won't be as easy as replacing the docker-image.

**Comment by keanesf** [comment]
I was able to reproduce the issue as well, when attempting to install the stripe payment module.

`
In PathValidator.php line 63:
                                                                                                                                    
  Path "/bitnami/magento/htdocs/app/code/StripeIntegration/Payments/view/base/templates/form/stripe-elements.phtml" cannot be used  
   with directory "/opt/bitnami/magento/htdocs/" 
 `

**Comment by javsalgar** [comment]
Indeed, we need to rethink the approach with this container. Note that we are working on the transition of our containers to bash. In this new model, we got rid of the symlinks. We'll need to figure out how to properly deal with these issues when we get there. We'll keep you updated.

**Comment by keanesf** [comment]
Are the symlink set in the magento-2.3.2-2 bitnami-pkg ? I ask as I do not see them set in the Dockerfile so it was unclear to me where they are specified.

**Comment by javsalgar** [comment]
This is done at initialization time. Check `/root/.nami/components/com.bitnami.magento/main.js`. It is when calling the function

```
    volumeFunctions.prepareDataToPersist($app.dataToPersist);
```

**Comment by gbitdev** [comment]
Hello.
I found that my problem have easy solution becouse this image have already way to do this.
Just change volume to presistent and add theme to this path. for e.g.
```
magento:
    image: 'bitnami/magento:2'
    environment:
...
    volumes:
      - './data/magento:/bitnami/magento'
```
and then put theme to` ./data/magento/desing/frontend/<Vendor>/<theme>`.
I think it should be in README.

**Comment by javsalgar** [comment]
Thanks for the contribution! Could the rest confirm that this works?

**Comment by mehrdadhosseinzadeh** [comment]
> I'm also facing similar kind of issue for custom module under `app/code`
> 
> Module is not registering when at `/opt/bitnami/magento/htdocs/app/code`
> But its registered at `/bitnami/magento/htdocs/app/code`
> Still unable to access from the browser.
> When I run `php magento setup:static-content:deploy -f`
> I'm getting the following.
> 
> ```
> In PathValidator.php line 63:
> 
>   Path "/bitnami/magento/htdocs/app/code/My/Module/view/frontend/templates/module.phtml" cannot
>    be used with directory "/opt/bitnami/magento/htdocs/"
> ```

i have same problem can you help me ?

i clone my theme in dockerfile from github and clone to /opt/bitnami/magento/htdoc/app/frontend/vendor/theme

but get same error 
please help me

**Comment by javsalgar** [comment]
Hi,

Please note that we are working on a major change in our Magento container, which will transition the logic to bash.  Pinging @marcosbc so he can let you know when the new container is available.

**Comment by marcosbc** [comment]
Hi @mehrdadhosseinzadeh, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

Please let us know if you find any issues installing themes with the new 2.4.1 Docker image, we'll be happy to help solve them.
