### ISSUE TITLE
Access denied for user 'bn_magento'@'172.29.0.3' (using password: YES)

### ISSUE THREAD

**Issue by GarryOne** [bitnami/bitnami-docker-magento#108]
**Description**
I've copied the `docker-compose.yml` template from this repo's `README.md` and without doing any modifications I ran `docker-compose up -d` and I got this error:
`Access denied for user 'bn_magento'@'172.29.0.3' (using password: YES)`

**Steps to reproduce the issue:**

1. Copy the contents from 
https://github.com/bitnami/bitnami-docker-magento#run-the-application-using-docker-compose 
to `docker-compose.yml`
2. Run 
```
$ docker-compose up -d
```

**Describe the results you received:**

I get the following error when I inspect the container's log:
`Access denied for user 'bn_magento'@'172.29.0.3' (using password: YES)`

**Describe the results you expected:**

To have a successful database connection and to see the magento up and running

**Additional information you deem important (e.g. issue happens only occasionally):**

I've entered into the mariadb container through ssh and tried to connect from that container's host, but the problem still persists.
More than that, I tried to use the root user, but setting `MARIADB_ROOT_PASSWORD` has no effect. The root's password remains still empty. 

**Version**

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

- Output of `docker info`:

```
$ docker info
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 55
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.933GiB
Name: linuxkit-025000000001
ID: TDJ6:MVLU:TRGX:MWOB:P6XR:XWHU:IASB:Z43F:GGWB:ODRA:J4L4:7GRG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 79
 Goroutines: 98
 System Time: 2019-06-06T15:36:05.3407776Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for MAC

**Comment by alemorcuq** [comment]
Hi, @GarryOne.

I'm not able to reproduce your issue. Both Magento and MariaDB start correctly using the `docker-compose.yml` file [from the README](https://github.com/bitnami/bitnami-docker-magento#run-the-application-using-docker-compose).

Let me suggest a couple of things that may be causing your error:

- Is it possible that you already have a volume initialized? You can bring it down with:

```
$ docker-compose down -v
```

- Is it possible that you are using an older image? Try downloading the latest images with:

```
$ docker-compose pull
```

If it's still failing, could you please post the entire log?

Regards,
Alejandro
