### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by amnakmahmood** [bitnami/bitnami-docker-magento#109]
How can you have sample data with this docker image?

**Comment by rafariossaa** [comment]
Hi @amnakmahmood,
  What do you mind exactly ? If it is possible to install sample data in the image or if we are going to release a image with the sample data already installed ?

  For the moment we are not going to release a docker image with the sample data, but, yes, it is possible to add the sample following the official steps, just take into account the PATHs of the binaries and data.

Best Regards,
Rafael Rios Saavedra

**Comment by amnakmahmood** [comment]
That worked, thanks!
