### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by vladimino** [bitnami/bitnami-docker-magento#112]
Hello there,

Thank you for the great product! I have the following question. As you may know, active support for PHP 7.1 ended on 1 Dec 2018, and after 1 Dec 2019, there won't be even security updates for this version. Taken this to account, are there any plans to upgrade the PHP version to 7.2 in this image?

Thanks in advance,
Vlad

**Comment by marcosbc** [comment]
Hi @vladimino, I've created an internal task for updating PHP to 7.2 in Magento containers as it seems to be supported. Unfortunately I cannot give an ETA for when it will be released, but we'll keep this issue updated with any progress.

**Comment by marcosbc** [comment]
Hi, just wanted to let you know we have released the Bitnami Magento container with PHP 7.2. Since this should be fixed, I'm closing the issue but feel free to add any comment if you find any issues or have any questions.
