### ISSUE TITLE
Option to enable all development options, including Xdebug

### ISSUE THREAD

**Issue by crfroehlich** [bitnami/bitnami-docker-magento#115]
It would be nice to start the container with all debug/developer options configured.

Current, manual steps:

* ~Enable Magento Development Mode~ (Already set)
  * ~`$ php bin/magento deploy:mode:set developer`~
* Enable PHP Display Errors
  * Open `/opt/bitnami/magento/htdocs/app/bootstrap.php`
  * Uncomment the line `ini_set('display_errors', 1);`
* Enable Magento 2 Display Errors
  * Rename `/opt/bitnami/magento/htdocs/pub/errors/local.xml.sample` > `/opt/bitnami/magento/htdocs/pub/errors/local.xml`
* Enable Template Path Hints
  * Open http://127.0.0.1/admin
  * Click Stores > Configuration > Advanced > Developer > Debug
  * Enable all options
* Enable Xdebug
  * `$ sudo apt-get update`
  * `$ sudo apt-get install git`
  * `$ sudo apt install build-essential`
  * `$ git clone https://github.com/xdebug/xdebug.git`
  * `$ cd xdebug`
  * `$ ./rebuild.sh` >
```
rm: cannot remove 'configure.in': No such file or directory
rm: cannot remove 'configure.ac': No such file or directory
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.
```
  * TBD: see https://devdocs.magento.com/guides/v2.3/cloud/howtos/debug.html

What is not clear is how to enable Xdebug per the official docs https://devdocs.magento.com/guides/v2.3/cloud/howtos/debug.html. There is no file `.magento.app.yaml` that I can find. I'm not sure how to proceed from there.

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for your suggestions. I am opening a internal task to our engineering team to study your proposals.

**Comment by marcosbc** [comment]
Hi @crfroehlich, Bitnami Magento already include XDebug by default, to enable it just uncomment the appropriate lines at `/opt/bitnami/php/etc/php.ini`.

Note that we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

This should make it a lot simpler for you to make these changes. Feel free to send a PR if you consider this is a feature that makes sense to support via envvars, we'll be happy to review and help with the release.
