### ISSUE TITLE
Can't control container services (Apache, php and so on)

### ISSUE THREAD

**Issue by AboElnoor** [bitnami/bitnami-docker-magento#116]
**Description**

**Steps to reproduce the issue:**

1. Install using the main docker-compose.yml file
2. docker-compose exec magento bash
3. `sudo /opt/bitnami/ctlscript.sh status`

**Describe the results you received:**

`sudo: /opt/bitnami/ctlscript.sh: command not found`
I ran `ls -a /opt/bitnami/`
and that all what I get
`.  ..  apache  base  bncert-tool  magento  mysql  nami	php  updates-ca-cert.pem`
**Describe the results you expected:**

I expected the results are here in this topic.
[Start Or Stop Services](https://docs.bitnami.com/bch/apps/magento/administration/control-services/)

**Comment by javsalgar** [comment]
Hi,

I'm afraid that this information is not for our containers, but for our cloud images. The way that container works is slightly different (for example, to be used in Kubernetes). Could you describe what you exactly were looking to do with the container?

**Comment by javsalgar** [comment]
You can add your custom certificates by mounting them at `/certs`

https://github.com/bitnami/bitnami-docker-magento#231-debian-9-r44-and-231-ol-7-r53

More info here

https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

Even though it is for the Apache container, it works the same here.

**Comment by AboElnoor** [comment]
> You can add your custom certificates by mounting them at `/certs`
> 
> https://github.com/bitnami/bitnami-docker-magento#231-debian-9-r44-and-231-ol-7-r53

But I'm not trying to install custom certificates.
I'm trying to enable HTTPS using the following tutorial:
[Use The Bitnami HTTPS Configuration Tool](https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#use-the-bitnami-https-configuration-tool)

**But I get this error:**

> Error: There has been an error.
Cannot bind to port 80 and/or 443. These ports are used for Let's Encrypt to verify the domain DNS configuration. Please stop any services using those ports, 
and ensure your system user has permissions to bind to them.

Not: I installed bncert-tool using the following tutorial because it does not exist too:
[Run The Bitnami HTTPS Configuration Tool](https://docs.bitnami.com/aws/how-to/understand-bncert/#run-the-bitnami-https-configuration-tool)

**Comment by javsalgar** [comment]
Hi,

That tool does not yet work with containers I'm afraid. Normally, in this kind of cases, what users do is to deploy Magento in a Kubernetes cluster that has cert-manager, ingress, externalDNS and other tools installed.

You can check an example here: https://docs.cert-manager.io/en/latest/tutorials/acme/quick-start/

The bitnami/magento chart has support for cert-manager, as you can see in this README: https://github.com/bitnami/charts/blob/master/bitnami/magento

If you want to use docker-compose and add a Let's Encrypt certificate, it is possible, but not something that we actively support. I found an example here: https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71

**Comment by AboElnoor** [comment]
I don't use Kubernetes. And I'm not planning to use it soon.

> If you want to use docker-compose and add a Let's Encrypt certificate, it is possible, but not something that we actively support. I found an example here: https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71

I have the same issue that I can't stop or restart the apache after installing the certificate.
What if I need to change some PHP settings, some apache settings? How to restart those services?
Please advise.
Thanks

**Comment by javsalgar** [comment]
Hi,

You could do `docker stop` and `docker start`, could you try that?

**Comment by AboElnoor** [comment]
That's not what I want, I want to stop the server to install certificates, so the container should be working but the webserver.
So, this way is not applicable to solve my issue.

**Comment by javsalgar** [comment]
The thing is that in WordPress only the Apache process is running. So if you stop the server, then the whole container would stop. What you could do is execute `docker-compose run wordpress bash` so it creates a shell without the server running. There you can install the certificates and then do docker-compose up as normal. Could you try that?
