### ISSUE TITLE
No product found after install

### ISSUE THREAD

**Issue by shajiahmed** [bitnami/bitnami-docker-magento#119]
I don't see any products in the store after install, usually magento comes with luma store. How do I get these products installed in docker
I am new to BitNami and Magento. I just started a  on BitNami  with Magento installed.

After the installation, I dont see any product loaded by default and the store is empty. Although Magento website has a sample data to start the store with, it has a pre-requisite that this sample data needs to be added to the mySQL database BEFORE the installation of Magento.

**Comment by jotamartos** [comment]
Hi @shajiahmed,

All our Magento solutions (container included) come with an empty store configured but we do not include any example data in the application so you can easily add any product you want to the application. 

You can find many tutorials on the internet about how to add new products to Magento (for example [this one](https://www.magestore.com/manage-magento-online-store/how-to-add-new-products-in-magento)). 

Let us know if you have any other questions about our solution.

Thanks
