### ISSUE TITLE
mounting /bitnami to local does not work

### ISSUE THREAD

**Issue by lblabr** [bitnami/bitnami-docker-magento#122]
i use your latest docker.

if i mount to local folder i get:

Autoload error
We can't read some files that are required to run the Magento application. This usually means file permissions are set incorrectly.

how can this be solved ?

without a mount to the local host it works.

thanks in advance

**Comment by alemorcuq** [comment]
Hi, @lblabr.

Can you share step by steps instructions on how to reproduce your issue?
