### ISSUE TITLE
Image 2.3.4 broken: Pod never gets into running state

### ISSUE THREAD

**Issue by stijnbrouwers** [bitnami/bitnami-docker-magento#130]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
**Description**
Magento pod is never getting in the running state since the last update of the 2.3.4 tag.
I am building a custom image, based on the magento:2.3.4 image. I use a custom image, because I was having issues with a custom theme because of how magento uses symlinks to point to persistent storage (See issue #113 ). To bypass the issue, I am using the solution provided by juan131 (https://github.com/bitnami/bitnami-docker-magento/issues/113#issuecomment-585674598).
You can find my nami.json and magento-inputs.json files here: [nami_files.zip](https://github.com/bitnami/bitnami-docker-magento/files/4318881/nami_files.zip)

Whenever I build the image from the previous image (by using the digest) everything works fine.
Switching back to the tag 2.3.4, breaks it again.

What I see in the Magento logs when booting the broken version is the following:
```
Welcome to the Bitnami magento container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
INFO  ==> Starting magento... 
Starting Apache...
```
The logs when using the digest (previous version) are the following:
```
Welcome to the Bitnami magento container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at gceurope-mariadb:3306
mysql-c INFO  MySQL server listening and working at gceurope-mariadb:3306
magento INFO 
magento INFO  ########################################################################
magento INFO   Installation parameters for magento:
magento INFO     Persisted data and properties have been restored.
magento INFO     Any input specified will not take effect.
magento INFO   This installation requires no credentials.
magento INFO  ########################################################################
magento INFO 
nami    INFO  magento successfully initialized
INFO  ==> Starting magento... 
Starting Apache...
[Wed Mar 04 15:47:13.454509 2020] [so:warn] [pid 122] AH01574: module rewrite_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.244.2.144. Set the 'ServerName' directive globally to suppress this message
```

So it seems something goes wrong in the magento initialization by the nami tool.

doing a curl provides the default apache 'it works' output, curling /index.php returns a 404 page not found. So apache is booted, but requests don't arrive @ magento.
This is also the reason why the pod doesn't get in the running state, the readiness probe looks for a 200 response from /index.php.

Any ideas on what might be wrong/broken since the latest updates?

**Steps to reproduce the issue:**
Use the 2.3.4 image tag 

**Describe the results you received:**
Magento never reaches "Running" state
**Describe the results you expected:**
Magento reaching "Running" state

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b07f53d
  Built:            Wed Jun 19 22:28:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Containers: 55
 Running: 45
 Paused: 0
 Stopped: 10
Images: 101
Server Version: 3.0.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1067-azure
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.769GiB
Name: xxx
ID: UHAT:7G3M:CAZF:PBPL:QFDA:V2LA:Y2FV:5S53:WWRE:SEFH:VGZY:2XBZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am running magento in Kubernetes in Azure (AKS).

**Comment by javsalgar** [comment]
Hi,

Our containers are tested before releasing so it must be the changes in the nami files that you are introducing in the fork the ones that are incompatible with the image. Could you provide a link to a github repository with your Dockerfile so we can try to build it on our own? Thanks

**Comment by stijnbrouwers** [comment]
Hi @javsalgar ,

Thanks for replying!
I created a github repo for this purpose: https://github.com/stijnbrouwers/magento-custom
Just one branch (master).

As you can see, currently, it is inheriting from tag 2.3.4 which gives the error.
When you inherit from the digest that is commented out (which is a previous version) you see that it will work.

Thanks for helping me out on this one!

**Comment by dani8art** [comment]
hi @stijnbrouwers, I can also see a difference in your logs, when you try with the broken version Magento is not being initialized, could you add `NAMI_DEBUG="--log-level=DEBUG" as environment variable to your deployment and send us back the logs, please?.

**Comment by stijnbrouwers** [comment]
@dani8art,

Thanks for your response, the result of setting the ENV variable is the following:
![image](https://user-images.githubusercontent.com/9864443/76967058-27c3b600-6927-11ea-89f2-d3fee50d5cfa.png)

**Comment by dani8art** [comment]
Hi @stijnbrouwers , it is wired because nami is not initializing magento, as you can see in the logs. please could you send us the exact dockerfile if possible? so that I can try to reproduce with the same data?

**Comment by stijnbrouwers** [comment]
Hi @dani8art,

The exact dockerfile can be found on github: https://github.com/stijnbrouwers/magento-custom
Changing the "FROM" statement shows that it's working for an old version of the image (use the digest) and it's not working for the latest version of the image (use 2.3.4 tag)

**Comment by dani8art** [comment]
Hi @stijnbrouwers , we made some changes in the nami files for magento and you need to reflect these changes in your custom ones, please could you try to apply theses diff to your files, maybe the lines are not the same for your files so try to do it manually.

```diff
--- ../nami.old.json	2020-03-23 08:20:34.921551222 +0000
+++ ../nami.new.json	2020-03-23 08:20:11.449066363 +0000
@@ -4,7 +4,7 @@
     "extends": [
         "Component"
     ],
-    "revision": "0",
+    "revision": "1",
     "author": {
         "name": "Bitnami",
         "url": "https://bitnami.com"
@@ -57,6 +57,15 @@
             ],
             "default": "default"
         },
+        "useSecureAdmin": {
+            "default": "no",
+            "type": "choice",
+            "validValues": [
+                "no",
+                "yes"
+            ],
+            "description": "Use SSL to access the Magento Admin"
+        },
         "externalHttpPort": {
             "description": "External port to access Magento application through HTTP",
             "default": "80"
``` 

```diff
--- ../magento-inputs.old.json	2020-03-23 08:19:13.203863167 +0000
+++ ../magento-inputs.new.json	2020-03-23 08:19:21.756039838 +0000
@@ -15,5 +15,6 @@
   "lastName": "{{$global.env.MAGENTO_LASTNAME}}",
   "mode": "{{$global.env.MAGENTO_MODE}}",
   "password": "{{$global.env.MAGENTO_PASSWORD}}",
+  "useSecureAdmin": "{{$global.env.MAGENTO_USE_SECURE_ADMIN}}",
   "username": "{{$global.env.MAGENTO_USERNAME}}"
 }
```

**Comment by stijnbrouwers** [comment]
@dani8art,

Thanks! That fixed it!
I applied it in my github repo and in our project and both work fine now.
Thanks for the help!
