### ISSUE TITLE
Error executing 'postInstallation': "size" argument must not be negative

### ISSUE THREAD

**Issue by 610492664** [bitnami/bitnami-docker-magento#131]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @610492664, please complete the New Issue template and provide more details on how we can reproduce this issue.

Also, please let us know if you can reproduce this issue with a simple docker-compose, if you made any change to Magento, or if it appears during the first initialization (without any persisted data).

**Comment by BarisJKC** [comment]
Hello,
I have the problem and logs from Magento service as per docker-compose.yml

> INFO  ==> Mounting certificates files from /certs...
nami    INFO  Initializing magento
Error executing 'postInstallation': "size" argument must not be negative

When the container runs w/o certs volume as below, it runs but I can not have my certs. When it runs with below volume, it stops and gives above problem in the log

>     volumes:
>      - "path/to/certs:/certs"

Any help is much appreciated.

Thank you

**Comment by marcosbc** [comment]
Let's continue the discussion on #159.
