### ISSUE TITLE
DB dump file

### ISSUE THREAD

**Issue by be-codified** [bitnami/bitnami-docker-magento#132]
Hi guys,

I am having issues with db dump as stated here:

https://stackoverflow.com/questions/61485612/magento-database-dump

Can I get some pointers what could be the issue?

Thank you in advance.

**Comment by javsalgar** [comment]
Hi,

I saw that you got the answer in the case from one of our Engineers. Could you confirm if that's the case?

**Comment by be-codified** [comment]
Hi @javsalgar,

yes, @jotamartos gave me the right answer, thank you. I think you can close this one down.
