### ISSUE TITLE
error in post install

### ISSUE THREAD

**Issue by kgoedert** [bitnami/bitnami-docker-magento#134]
Hi, I had a version of magento working on an image I had downloaded earlier this week. Everything was working.
I had to delete all my images and containers and I just downloaded everything again.
When the containers start I get this error from magento

Error executing 'postInstallation': ENOENT: no such file or directory, chown '/bitnami/magento/htdocs/app/code/Magento'

I tried to remove all containers and images again, but the error persists

**Comment by kgoedert** [comment]
The error is only happening on mac os. I just tested it on a linux box and it works. Any ideia how can I make this work on a mac?

**Comment by juan131** [comment]
Hi @kgoedert 

Did you clean/remove the attached volumes too? For instance, if you're using `docker-compose` you can remove the volumes using the `-v` flag:

```bash
$ docker-compose down -v
$ docker-compose up -d
```

**Comment by kgoedert** [comment]
Removing the volumes did the trick. Thanks
