### ISSUE TITLE
MAGENTO_HOST always redirects 

### ISSUE THREAD

**Issue by kgoedert** [bitnami/bitnami-docker-magento#135]
In a linux box, when I set MAGENTO_HOST to an ip address in my private network, I get an endless redirect in the url like this:

http://10.1.1.79/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79index.php/10.1.1.79in....

and a message 403 forbidden.
Checking the core config data table the information seems to be correct.

```
 3 | default  |        0 | web/unsecure/base_url                                            | 10.1.1.79                                                                                                                                       | 2020-05-07 14:18:26 |
|         4 | default  |        0 | web/secure/base_url                                              | 10.1.1.79
````
How can I fix this?

**Comment by javsalgar** [comment]
Hi,

Does the same issue happen when you configure the site using a domain name?

**Comment by kgoedert** [comment]
yes... the same weird redirects.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I just used the example docker-compose.yml and set the MAGENTO_HOST variable to a custom domain. 

![image](https://user-images.githubusercontent.com/1133777/81563869-2d71d100-9397-11ea-8f8e-36dc5ac7ba34.png)

Could you try doing docker-compose down -v and docker-compose up again? (make sure that you back up any important data before)

**Comment by niteshldd** [comment]
Using MAGENTO_USE_SECURE_ADMIN: Use SSL to access the Magento Admin. Valid values: yes, no. Default: no 

May work
