### ISSUE TITLE
bitnami-pkg magento 2.3.4.2 is not the right version

### ISSUE THREAD

**Issue by iphigenie** [bitnami/bitnami-docker-magento#141]
This isn't exactly a "bug" but I just wasted a morning trying to figure out what was wrong with my understanding of docker, my machine, my installation, bitnami's way of doing things, local docker image caches etc. 

I thought it was not getting the right tagged version because of local / configuration issues

But it turns out that the files downloaded into the container by lines like 

`bitnami-pkg unpack magento-2.3.4-2 --checksum a063f3b60ceeb46f1f1c7f0aa84432d1203af42a70b6af42553be7fe815b9479`
actually are of magento-2.3.4 without the patches 

bitnami-pkg unpack magento-2.3.4-1 is the same

So we think we are requesting and building a "latest" 2.3.4-2 version but we are getting a 2.3.4 unpatched

**Comment by joancafom** [comment]
Hi @iphigenie ,

I am currently reviewing your issue and I will keep you informed about my findings on the matter. What is the main characteristic that makes you suspect version `2.3.4-2` is actually `2.3.4` ?

Thanks!

**Comment by iphigenie** [comment]
Hi @joancafom 

I tried installing this docker stack using tag version 2.3.4-debian-10-r78  its Dockerfile fetches that package - and what I got installed was magento 2.3.4 

It replied 2.3.4 to bin/magento --version and showed 2.3.4 in admin.

I ran the bitnami-pkg manually to get the files again
they end up in  /tmp/bitnami/pkg/install/magento-2.3.4-2-linux-amd64-debian-10/files/magento/

if you look at the composer.json files it says 
   "require": {
        "magento/product-community-edition": "2.3.4"
    },

It should say

    "require": {
        "magento/product-community-edition": "2.3.4-p2"
    },

**Comment by joancafom** [comment]
Hi again @iphigenie !

I have investigated the issue and I can tell you that a package named `magento-2.3.4-X` does not make a direct reference to the patch version `pX`. This naming pattern addresses an intermediate artifact used to deploy the application (nami). Hence, it is possible that packages `magento-2.3.4-X` share the same Magento version.  

Nevertheless, I am going to create an internal task to review the versions that are delivered in this docker image. Thank you for your report!

**Comment by iphigenie** [comment]
Hi @joancafom 

I think what is needed is consistency and clarity and perhaps a note in the container documentation so people understand the logic and can work out their workflow around it.

The presence or not of patches needs to be obvious. Maybe you never patch and say so.

The challenge I have is that if I update my container manually to have the patches, the next time the container is upgraded the patch is reversed, I have no idea what mess I might end up with.
The persisted magento database will already be patched, but the code will be back to unpatched. 

I think the documentation could just use a best practice around how you patch and add modules in the most "works with our bitnami updates" way so we don't have to trial and error it

**Comment by joancafom** [comment]
Hi @iphigenie 

By default, Bitnami closely tracks new changes in the upstream source and changes its docker images accordingly, using the latest `stable` release in a given moment. That is, if the current `stable` upstream release includes patches, it expected to find those in our images too. What you are reporting is an unexpected behaviour, and hence I created an internal task to further investigate what is happening. 

We take security very seriously and hence periodically perform a [CVE scan](https://quay.io/repository/bitnami/magento?tab=tags) to the releases we deliver.

Thank you so much for reporting this!

**Comment by iphigenie** [comment]
Of course you are right - I played with doing a composer require ... update to get the patch, and of course that replaces all your customised htaccess files and possibly other changes I am not aware of it.
The patch has to be in the container distribution, not added to it by composer.

**Comment by joancafom** [comment]
Yes, we are working on this issue but unfortunately we can not provide you with an ETA. We are also considering your feedback about version naming. On the mean time, you can always upgrade to our latest current version (which is `2.3.5` and includes the latest `p1` patches).

Thanks!

**Comment by marcosbc** [comment]
This should already be fixed now that Magento 2.4.1 is out, so I'm closing this issue. Feel free to let us know if you'd like it re-opened.
