### ISSUE TITLE
Skipping reindexing step while running magento 2.3.4 docker image 

### ISSUE THREAD

**Issue by RachakondaSamhitha** [bitnami/bitnami-docker-magento#142]
**Description**

Installing Magento 2.3.4 in GKE platform using bitnami/magento-2.3.4 docker image and an existing db with size 14 GB. When deploying this image, the initial startup time is taking about 35 mins. It was observed that Reindexing step is taking about 15-20 mins. So, wanted to skip that step evertime the application is deployed. 

**The following are the logs obtained when bitnami/magento image is being deployed to GKE:**
-----------------------------------------------------------------------
Welcome to the Bitnami magento container
Subscribe to project updates by watching ehttps://github.com/bitnami/bitnami-docker-magentoe
Submit issues and feature requests at ehttps://github.com/bitnami/bitnami-docker-magento/issues
Send us your feedback at econtainers@bitnami.come

nami INFO Initializing apache
nami INFO apache successfully initialized
nami INFO Initializing php
nami INFO php successfully initialized
nami INFO Initializing mysql-client
nami INFO mysql-client successfully initialized
nami INFO Initializing magento
magento INFO Preparing Magento environment...
magento INFO Installing Magento...
magento INFO Deploying to developer mode...
magento INFO Configuring Elasticsearch...
magento INFO Reindexing...
magento INFO Flushing cache...
magento INFO

magento INFO Installation parameters for magento:

magento TRACE [exists] File normalization: /bitnami/magento/.restored -> /bitnami/magento/.restored

magento INFO Username: samhitha

magento INFO Site URL:

magento INFO Admin URL:

magento INFO This installation requires no credentials.

magento INFO

magento INFO
nami INFO magento successfully initialized

==> Starting gosu...
.....
-----------------------------------------------------------------

**Describe the results you received:**

Reindexing taking about 20 mins when magento application is getting deployed on GKE.

**Describe the results you expected:**

Way to skip reindexing step while installing magento.

**Version**

- Output of `docker version`:

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 128
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: NRUU:JAJS:TIGN:6EZD:LAOK:453K:2GSJ:WW7D:75CD:XFDE:OONZ:HJFX
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 29
  Goroutines: 45
  System Time: 2020-05-25T17:02:36.3270362Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Google Kubernetes Engine

**Comment by marcosbc** [comment]
Hi, this looks like a feasible change. I'm creating an internal task for implementing it, and will get back to you with any update.

**Comment by marcosbc** [comment]
Hi, we just implemented a fix via the `magentoSkipReindex` option in `values.yaml`. We're considering this solved, but if you find any issues let us know.

**Comment by RachakondaSamhitha** [comment]
Hi  Marcos Bjoerkelund,
Thank you for fixing this issue. Will let you know if we have any other
concerns.

Regards,
Samhitha.
