### ISSUE TITLE
Default admin user/ password ?

### ISSUE THREAD

**Issue by sgmihai** [bitnami/bitnami-docker-magento#145]
I tried for more than one hour to access the admin panel and nothing works. what I did:
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
-> tried http://localhost/admin with user/bintami1 as per the defaults and what was set as environment options when I checked the container with the kitematic gui. I also tried to change them  from that gui to something else, and it sill would not work to log in.

Then I deleted the containers and edited  docker-compose.yml adding these 4 entries:
  magento:
    image: 'bitnami/magento:2'
    environment:
      - MAGENTO_PASSWORD=mypassword1234
      - MAGENTO_USERNAME=myuser
      - MAGENTO_EMAIL=user@example.com
      - MAGENTO_ADMINURI=admin

and then sudo docker-compose up -d
Neither these user/pass combinations work. So please tell me what am I doing wrong. Almost two hours of googling and cannot login :( I think I could install magento 2 times in the meantime.

**Comment by sgmihai** [comment]
Update, it seems to be a probem related to firefox. Chromium and Opera worked from the first try. I somehow managed to log in with firefox after I posted the previous message, not sure exactly what I did. But now after building the containers from scratch again, it does not work again. I tried clearing cookies and cache, didn't help. It just goes back to the login screen.

**Comment by carrodher** [comment]
Hi, I am trying to reproduce your issue but I was not able. For me both methods are working fine:
- Default parameters (`user/bitnami`)
- Custom env. variables (`myuser/mypassword1234`)

I was testing everything in Chrome, but after read your comment I repeated all the tests using Firefox:

<img width="1279" alt="Screenshot 2020-06-01 at 14 04 24" src="https://user-images.githubusercontent.com/13216600/83407333-cf259480-a410-11ea-8ac7-96cf4b514044.png">

As you can see in the screenshot, everything is working. I tried both URLs: http://127.0.0.1/admin and http://localhost/admin, just in case some weird issue with the redirections. Are you able to see any error in the development console or something like that?

**Comment by sgmihai** [comment]
I tried it with a different version of firefox.. and it worked, so not firefox specific probably. I left it be, and after a few hour tried to log in again, with the initially non working firefox. And it worked. Very very strange :-?

**Comment by carrodher** [comment]
That kind of things happens from time to time 😄  Anyway, I am glad that everything is up and running right now, please don't hesitate to post a new message if you find something else
