### ISSUE TITLE
simplifying magento commandline

### ISSUE THREAD

**Issue by Fuseteam** [bitnami/bitnami-docker-magento#147]
with [magento deprecating the web setup wizard](https://devdocs.magento.com/guides/v2.3/install-gde/install/web/install-web.html) the syntax for using magento commandline feels a bit.....long
afaict the command currently is `docker-compose exec magento /opt/bitnami/magento/htdocs/bin/magento magento_command`
perhaps with a symlink it could be simplified to
`docker-compose exec magento magento magento_command`

**Comment by miguelaeh** [comment]
Hi @Fuseteam ,
Thank you very much for reporting this.
I think it could be a better solution to include that binary in the `PATH` so it would be possible to directly execute it. 
I am checking the container and it seems that binary is not executable, so maybe we also need to grant execution permissions to the binary.
What do you think about that?

**Comment by Fuseteam** [comment]
@migmartri that sounds like a good solution :+1:

**Comment by miguelaeh** [comment]
Hi @Fuseteam ,
I have created an internal task to take care of this issue. 
Thank you very much for reporting it!

**Comment by Fuseteam** [comment]
thanks @miguelaeh i look forward to the fix

**Comment by flexchar** [comment]
Heads up! I pulled latest `bitnami/magento:2.4.0` image and Magento CLI is added to the global path

**Comment by Fuseteam** [comment]
awesome i'll check it out when i have the chance

**Comment by miguelaeh** [comment]
Hi guys,
We implemented that but it seems we forgot to update this thread. Sorry for the inconvenience!

**Comment by Fuseteam** [comment]
ohw cool thank you, i haven't had a chance to update yet, i will report back when i get the chance

**Comment by Fuseteam** [comment]
finally managed to confirm this works! thanks!
