### ISSUE TITLE
deploy sample data and credentials to the Magento Marketplace via ENV

### ISSUE THREAD

**Issue by androdebugur** [bitnami/bitnami-docker-magento#148]
Hi, I need some help to update this file bitnami/magento [docker-compose.yml](https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml) file, so that when it is run it deploys the sample data by default. I believe it will also need increase of memory and Magento credentials via ENV variables. Thank you very much.

**Comment by marcosbc** [comment]
Hi @androdebugur, Magento offers documentation on how to deploy the sample data after installing, see: https://devdocs.magento.com/guides/v2.3/install-gde/install/sample-data-after-composer.html

Currently the Bitnami Magento container image doesn't support it, and we don't think it would add significant value either if we automate that, as users can easily run a couple of commands to add the sample data to their installation when desired. In any case, we would like to know your use case. Why is it you want to have sample data deployed automatically with Magento?

Note that you should be able to automate it, without requiring a new Docker image, via cusotm init scripts. To do that, mount a .sh file to the container such as `/docker-entrypoint-init.d/populate-sample-data.sh`:

```bash
#!/bin/bash

# CHANGEME: Set Magento auth keys
/opt/bitnami/php/bin/composer global config http-basic.repo.magento.com "<public_key>" "<private_key>"

# Deploy sample data
/opt/bitnami/magento/htdocs/bin/magento sampledata:deploy

# Upgrade database
/opt/bitnami/magento/htdocs/bin/magento setup:upgrade
```

To use this file, change your `docker-compose.yml`:

```diff
@@ -24,6 +24,7 @@
       - '443:443'
     volumes:
       - 'magento_data:/bitnami'
+      - './populate-sample-data.sh:/docker-entrypoint-init.d/populate-sample-data.sh'
     depends_on:
       - mariadb
       - elasticsearch
