### ISSUE TITLE
Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144

### ISSUE THREAD

**Issue by nabeelaejaz** [bitnami/bitnami-docker-magento#151]
**Description**

Docker on Windows - Elasticsearch doesn't run. Logs show error: ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144

**Steps to reproduce the issue:**

1. docker-compose up -d
2. Elasticsearch does not run. The bitnami tries to install it then shutdowns bitnami_magento_1 as well.

**Describe the results you received:**

Check screenshot: http://tca.com.pk/upload/uploads/Image%201.png

**Describe the results you expected:**

Expect it to run

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
2.3.0.3 stable
```

**Comment by javsalgar** [comment]
Hi, 

In order to launch Elasticsearch you need to change some Kernel settings. I am not sure how Docker for Windows works under the hood, but if it has a Linux VM that you can access, then you could execute the following command:

```
sudo sysctl -w vm.max_map_count=262144
sudo sysctl -w fs.file-max=65536
```

**Comment by janpjens** [comment]
For thise experiencing this problem under Windows 10 with Docker desktop (WSL 2): You can solve it by first starting the WSL shell with the `wsl` command from the command line, then running `sysctl -w vm.max_map_count=262144` from there.

**Comment by javsalgar** [comment]
Thank you very much for the tip! :D

**Comment by micc83** [comment]
For those getting here, unable to solve the issue on Powershell, as seen [here](https://discuss.elastic.co/t/elasticsearch-config-issues-sshing-into-default-linux-machine/182804/2), I'd suggest trying the following:

```shell script
# Get a privileged container with access to Docker daemon
docker run --privileged -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker alpine sh

# Exit the shell if needed
exit

# Run a container with full root access to MobyLinuxVM and no seccomp profile (so you can mount stuff)
docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh

# Switch to host FS
chroot /host

# And now set the value (sudo if needed)
sysctl -w vm.max_map_count=262144
```

**Comment by sivamind** [comment]
from windows search wsl then run sysctl -w vm.max_map_count=262144
Now issue is resolved

**Comment by javsalgar** [comment]
Awesome! Thanks for sharing solutions :D
