### ISSUE TITLE
https certificates renewal

### ISSUE THREAD

**Issue by Hrnkas** [bitnami/bitnami-docker-magento#152]
### **Since I haven't find any documentation on how to renew the installed https certificates, here is my solution.**

**My Setup:**
 - Bitnami Magento composition including magento, mariadb and elasticsearch.
 - Reverse Proxy on the host machine to redirect http and https trafic to the docker container.
 - Real Certificates are installed on the host machine.
 - magento container has the default certificates that came with the package (valid only 3 months from installation)

**My Problem:**
 - proxy Error during SSL Handshake with remote server
 - cause of the error: certificates in the magento container have expired
 - using bncert-tool does not work, since it needs ports 80 and 443, but they are blocked by magento (httpd) service

**My Solution (using openssl):**

_1. get into the container using bash_
`docker exec -it magento_magento_1 bash`

_2. Backup the existing certificate and key_
`mkdir backup && cp server.* backup/.`

_3. create new Code Signing Request (CSR) using existing key:_
`openssl req -new -key server.key -out server.csr`

_4. create new Certificate (Valid for 10 years):_
`openssl x509 -req -in server.csr -days 3650 -signkey server.key -out new_server.crt`

_5. replace old Certificate with the new one:_
`mv server.crt old_server.crt && mv new_server.crt server.crt`

_6. Restart the container:_
Exit the container: `exit`
Back in the host: `docker-compose restart`

**Comment by juan131** [comment]
Thanks so much for sharing your solution @Hrnkas !! We really appreciate it.

Alternative: why not managing HTTPS connections at Proxy Level? Keeping connections between the Proxy and Magento using HTTP. Sth like this:


User ---> HTTPS connection ---> Proxy (manages certificate) ---> HTTP Connection ---> Magento (ignores certificates)
