### ISSUE TITLE
Unable to make graphql mutation, error occurs "Schema is not configured for mutations."

### ISSUE THREAD

**Issue by codemasternode** [bitnami/bitnami-docker-magento#157]
**Description**

**Steps to reproduce the issue:**

1. I open Graphql Client and fill URL
2. Next, i write mutation, it's copy and paste from Magento 2.4 documentation: https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-customer.html
`mutation { createCustomer( input: { firstname: "Bob" lastname: "Loblaw" email: "bobloblaw@example.com" password: "b0bl0bl@w" is_subscribed: true } ) { customer { firstname lastname email is_subscribed } } }`
3. I send the request and getting an error:
`{ "errors": [ { "message": "Schema is not configured for mutations.", "locations": [ { "line": 1, "column": 1 } ], "stack": [ "GraphQLError: Schema is not configured for mutations.", " at getOperationRootType (/home/marcin/projects/a24store/frontend/node_modules/graphql/utilities/getOperationRootType.js:28:13)", " at executeOperation (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:210:61)", " at executeImpl (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:104:14)", " at execute (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:64:35)", " at /home/marcin/projects/a24store/frontend/node_modules/express-graphql/index.js:152:16", " at processTicksAndRejections (internal/process/task_queues.js:97:5)" ] } ], "extensions": {} }`
4. When i'm trying to make other mutation call like for example createToken, the same error occurs (like above)

**Describe the results you received:**
I'm getting error:
`{ "errors": [ { "message": "Schema is not configured for mutations.", "locations": [ { "line": 1, "column": 1 } ], "stack": [ "GraphQLError: Schema is not configured for mutations.", " at getOperationRootType (/home/marcin/projects/a24store/frontend/node_modules/graphql/utilities/getOperationRootType.js:28:13)", " at executeOperation (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:210:61)", " at executeImpl (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:104:14)", " at execute (/home/marcin/projects/a24store/frontend/node_modules/graphql/execution/execute.js:64:35)", " at /home/marcin/projects/a24store/frontend/node_modules/express-graphql/index.js:152:16", " at processTicksAndRejections (internal/process/task_queues.js:97:5)" ] } ], "extensions": {} }`

**Describe the results you expected:**
Like in documentation, response should be:
`{ "data": { "createCustomer": { "customer": { "firstname": "Bob", "lastname": "Loblaw", "email": "bobloblaw@example.com", "is_subscribed": true } } } }
`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 18.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.53GiB
 Name: marcin-System-Product-Name
 ID: WVOS:IRZ4:V3KO:LGPX:WOSM:4JMS:HHQO:ROEE:D7X7:RQDO:7FXU:OCF3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Looking at the error, it seems to me that it is upstream, as we are not changing any GraphQL settings. I see that you opened a ticket here: https://github.com/magento/magento2/issues/29864

Let's wait for the devs to comment on the issue, and if there's anything that we need to change on our side.
