### ISSUE TITLE
Bitnami/Magento2 open source with Docker

### ISSUE THREAD

**Issue by BarisJKC** [bitnami/bitnami-docker-magento#158]
System Setup: 

CPU: 8 CPU 

RAM: 8 GB 

SSD: 100 GB 

OS: Ubuntu 18.04 

Control Panel: Plesk 

Magento Ver: 2.3.5-p1 

 

We are trying to build an e-commerce site with Magento 2. 

Plesk is installed on Ubuntu  

The basic setup on separated containers (elasticsearch, mariadb, magento) with docker-compose has no problem when only IP and port are used. Updated compose file contains 

https://github.com/bitnami/bitnami-docker-magento (instead of magento 2.4, we use 2.3) 

environment: 

- APACHE_ENABLE_CUSTOM_PORTS=yes 

- EXTERNAL_HTTP_PORT_NUMBER=8020 

- APACHE_HTTP_PORT_NUMBER=80 

- EXTERNAL_HTTPS_PORT_NUMBER=5443 

- APACHE_HTTPS_PORT_NUMBER=443 

ports: 

- "8020:80" 

- "5443:443" 

 

But when we try to bind a domain name and add ssl (including Plesk docker proxy rules are used to redirect traffic for domain name to the selected container and port) via plesk admin panel the system goes problematic. 

  

- Site cannot be accessed without using browser in incognito mode 
 
- Adds port number at the end of the domain 
 
- Admin URL is not reachable at all  
 
- Admin page redirects endlessly to the same login page according the logs 

Domain: For testing purposes we use domain from https://www.freenom.com/ 

SSL: Let’s Encrypt provided by Plesk Panel 

 

We couldn’t solve the issue here... 

You may check the test site on the following addresses. 

www.magentotest.gq 

http://www.magentotest.gq:8020/index.php

**Comment by FraPazGal** [comment]
Hello @BarisJKC,

I'm not sure how much I can help you regarding plesk and your hosting provider, but it's seems you have been working on this as I couldn't access the links this morning and now I'm redirected to [https://www.magentotest2.gq/](https://www.magentotest2.gq/). 

From what I can see, you have solved your non-incognito access problem as well as the port number at the URL one. Regarding the Admin URL, have you set the environment variable `MAGENTO_USE_SECURE_ADMIN=yes`?. Its value is `no` by default, but you need to change it if you are using SSL .

**Comment by BarisJKC** [comment]
> Hello @BarisJKC,
> 
> I'm not sure how much I can help you regarding plesk and your hosting provider, but it's seems you have been working on this as I couldn't access the links this morning and now I'm redirected to https://www.magentotest2.gq/.
> 
> From what I can see, you have solved your non-incognito access problem as well as the port number at the URL one. Regarding the Admin URL, have you set the environment variable `MAGENTO_USE_SECURE_ADMIN=yes`?. Its value is `no` by default, but you need to change it if you are using SSL .

Hola y gracias,
We had an SSL isue and fixed that and updated admin secure url as well. It started to work.
