### ISSUE TITLE
Error adding custom content to bitnami image

### ISSUE THREAD

**Issue by evanshoshan** [bitnami/bitnami-docker-magento#161]
**Description**
I am deploying the bitnami magento helm chart with the magento:2 docker image and I am unable to get pods to start due to failure while pod is initializing.

Dockerfile congaing copy commands to move custom code and media into docker image:

```
FROM bitnami/magento:2

COPY /app /opt/bitnami/magento/htdocs/app
COPY /pub/media /opt/bitnami/magento/htdocs/pub/media

RUN chown -R bitnami:daemon /opt/bitnami/magento/htdocs
RUN chmod -R 777 /opt/bitnami/magento/htdocs/app
```

Logs of the pod

```
magento INFO  Installing Magento...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php magento,setup:install,-v,--base-url,http://magento.xenaana.apps.jnj.com/,--backend-frontname,admin,--db-host,magento-mariadb:3306,--db-name,shop,--db-user,user,--db-password,jnj12345678,--admin-firstname,FirstName,--admin-lastname,LastName,--admin-email,user@example.com,--admin-user,user,--admin-password,jnj12345678,--language,en_US,--currency,USD,--timezone,America/Los_Angeles,--use-secure,1,--base-url-secure,https://magento.xenaana.apps.jnj.com/,--use-secure-admin,0,--elasticsearch-host,magento-elasticsearch-coordinating-only
Error executing 'postInstallation': 
In Installer.php line 923:
                                                     
  [Exception]                                        
  Missing write permissions to the following paths:  
  /opt/bitnami/magento/htdocs/app/etc                
                                                     

Exception trace:
  at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:923
 Magento\Setup\Model\Installer->throwExceptionForNotWritablePaths() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:506
 Magento\Setup\Model\Installer->checkInstallationFilePermissions() at n/a:n/a
 call_user_func_array() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Model/Installer.php:372
 Magento\Setup\Model\Installer->install() at /opt/bitnami/magento/htdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:231
 Magento\Setup\Console\Command\InstallCommand->execute() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/magento/htdocs/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/magento/htdocs/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at /opt/bitnami/magento/htdocs/bin/magento:23
```

**Steps to reproduce the issue:**

1.Create dockerfile from base magento image tagged version 2
2. Copy files from /app directory to /opt/bitnami/magento/htdocs/app
3. Copy files from /pub/media directory to /opt/bitnami/magento/htdocs/pub/media
4. Change ownership of files to bitnami:daemon
5. Run helm upgrade 
6. Check logs of magento pod

**Describe the results you received:**

Error is thrown in Installer.php file saying that files are not writable

**Describe the results you expected:**

Pod is created and static content is deployed.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS EKS cluster

**Comment by FraPazGal** [comment]
Hi @evanshoshan,

I have followed your steps but I haven't been able to reproduce your issue. Could you please review my logs and share yours on case there is anything different?

```
$ kubectl get pods

NAME                                                       READY   STATUS    RESTARTS   AGE
magento-5dc8ffd86c-pp8b8                                   1/1     Running   0          6m6s
magento-elasticsearch-coordinating-only-8675b77c44-8gjsr   1/1     Running   0          7m43s
magento-elasticsearch-data-0                               1/1     Running   0          7m43s
magento-elasticsearch-master-0                             1/1     Running   0          7m43s
magento-mariadb-0                                          1/1     Running   0          7m43s
```

I also searched for the file that I copied using the Dockerfile:

```
$ kubectl exec --stdin --tty magento-5dc8ffd86c-pp8b8 -- bin/bash

root@magento-5dc8ffd86c-pp8b8:/# ls opt/bitnami/magento/htdocs/app/
autoload.php  bootstrap.php  design  etc  test.txt
```

From what your logs say, it seems the files permissions got changed at some point other than at build time of the new image. Did you use your custom image both in `helm install` and `helm upgrade`? The upgrade command showed when the chart is deployed uses the chart from the repo, `bitnami/magento`.

In the meantime, could you please try to apply this changes to your deployment? They may help you solve the issue:

- Try to only change the owner/permissions of the copied files. Also, as a security concern, try to only give them the minimum required permissions (775 for folders and 664 for files).
- I'm not sure if you are creating a new image to copy the files out of necessity but, if you can, I think it would be easier to mount those files using a persistent volume in kubernetes and leaving aside the magento image.
