### ISSUE TITLE
How to update CORS policy in Magento 2.4, where ?

### ISSUE THREAD

**Issue by codemasternode** [bitnami/bitnami-docker-magento#162]
**Description**
How to update CORS policy in Magento 2.4 version, where ? I would like to add domain http://xxxxx as origin.

**Version**

Magento 2.4

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.53GiB
 Name: marcin-System-Product-Name
 ID: WVOS:IRZ4:V3KO:LGPX:WOSM:4JMS:HHQO:ROEE:D7X7:RQDO:7FXU:OCF3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by codemasternode** [comment]
/opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf - update this file

**Comment by codemasternode** [comment]
/opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf - just update this file

**Comment by adampwright** [comment]
Do filenames/paths in this project keep changing? I keep running into disparities between advice given and actuality. ``

On this subject: I can't get my CORS policy updated to  fix this error "Access to XMLHttpRequest at 'http://localhost/index.php/rest/V1/integration/admin/token' from origin 'http://localhost:8100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check:"

I am changing as close as there is available file (from above advice from:

`<VirtualHost 127.0.0.1:8080 _default_:8080>
  ServerAlias *
  DocumentRoot /opt/bitnami/magento
  <Directory "/opt/bitnami/magento">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
`

to 

`<VirtualHost 127.0.0.1:8080 _default_:8080>
  ServerAlias *
  DocumentRoot /opt/bitnami/magento
  <Directory "/opt/bitnami/magento">
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    Header set Access-Control-Allow-Origin "*"
  </Directory>
</VirtualHost>
`

then restarting. But to no avail. 

Can anyone advise on this issue? Thanks

**Comment by andresbono** [comment]
Hi @adampwright, the Magento container had a major refactor recently, see https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80. That's why you can find discrepancies with what is advised in old issues.

How are you using the container? With docker-compose? How do you restart? Are you persisting `/opt/bitnami/apache/conf/vhosts/magento-vhost.conf`?

Can you check if your change is being applied? You can get the http headers and see if the one you are setting is returned:

```console
$ docker-compose exec magento curl -sI localhost:8080 | grep Access-Control-Allow-Origin
Access-Control-Allow-Origin: *
```

**Comment by adampwright** [comment]
Hi @andresbono. I am using the container with Docker-Compose with Docker Desktop (Windows) using the GUI to stop and then start the container. After running your command, it appears that the file change is persisting correctly, with a response of "Access-Control-Allow-Origin: *". Alas, still the same "Access to XMLHttpRequest at 'http://localhost/index.php/rest/V1/integration/admin/token' from origin 'http://localhost:8100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status." error. 

Here is my docker-compose file, if it helps. 

`
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_MEMORY_LIMIT=-1
      - MAGENTO_USERNAME=xxx(hidden)
      - MAGENTO_PASSWORD=xxx(hidden)
      - MAGENTO_EMAIL=xxx(hidden)
      - MAGENTO_MODE=developer
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

`

Help appreciated!

**Comment by andresbono** [comment]
I'm not sure what is going on...

```
[...] from origin 'http://localhost:8100 [...]
```

How is the 8100 port involved?

Maybe you can check the headers in the web browser to determine if the `Access-Control-Allow-Origin` is being set

**Comment by adampwright** [comment]
> How is the 8100 port involved?
> 

8100 is my Angular/Ionic app that is making the HTTP request. I'll have a dip into their documentation to see if it's an issue this end.
