### ISSUE TITLE
[feature request] environment variables for redis

### ISSUE THREAD

**Issue by Fuseteam** [bitnami/bitnami-docker-magento#165]
magento is a rather cache heavy webapplication, configuring it to use a redis server makes it much more usuable in my experience
i managed to append my docker-compose file to use the bitnami redis docker image
after setup of magento i can then setup redis as the cache-backend and page cache using the following commands

```
docker-compose magento magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=0
docker-compose exec magento magento setup:config:set --page-cache=redis --page-cache-redis-server=redis --page-cache-redis-db=1
```

would it be possible to set this up via environment variables in the same way elastic search is set up?

**Comment by miguelaeh** [comment]
Hi @Fuseteam ,
Thank you very much for requesting this feature. I will create an internal task to review this. We cannot provide an ETA for it, but we will update this thread once we have news.
Regards.

**Comment by Fuseteam** [comment]
thanks as always @miguelaeh

**Comment by marcosbc** [comment]
Hi, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

In particular, one of the new environment variables is `MAGENTO_EXTRA_INSTALL_ARGS` which you can use to pass `--cache-backend=redis` and other flags (separated by spaces).

If you wish to implement this feature officially in the image, now that the source code for the initialization was open sourced, feel free to send a PR! We'd be happy to help with the review and release of the new Docker image.

**Comment by Fuseteam** [comment]
awesome thanks @marcosbc i'll take a look at how that works when I get a chance
