### ISSUE TITLE
admin panel not accessible with custom ports

### ISSUE THREAD

**Issue by Fuseteam** [bitnami/bitnami-docker-magento#166]
**Description**

if i set the custom ports using EXTERNAL_HTTPS_PORT_NUMBER=62443 and i set admin to use secure ssl using MAGENTO_USE_SECURE_ADMIN=yes i cannot access the admin panel at magento2.shop:6262/admin

**Steps to reproduce the issue:**

1. set EXTERNAL_HTTPS_PORT_NUMBER=62443
2. set MAGENTO_USE_SECURE_ADMIN=yes
3. set MAGENTO_HOST=magento2.shop

**Describe the results you received:**

i get error 404
![2020-10-21-091413_1922x1014_scrot](https://user-images.githubusercontent.com/10421851/96884443-e3b60800-1457-11eb-9cbf-59968b0c6278.png)

**Describe the results you expected:**

i expect the login page for the admin panel

**Version**

- Output of `docker version`:

```
(paste your output here)Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 9
  Paused: 0
  Stopped: 24
 Images: 355
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local local-persist
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-121-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.527GiB
 Name: fuseteam
 ID: 2FFJ:NNX2:KX5R:IVDT:CBKK:KCUY:AAJF:D6ZN:7UBU:KVIK:X2O4:JDY7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: fuseteam
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build unknown
docker-py version: 4.1.0
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by juan131** [comment]
Hi @Fuseteam 

> if i set the custom ports using EXTERNAL_HTTPS_PORT_NUMBER=62443 and i set admin to use secure ssl using MAGENTO_USE_SECURE_ADMIN=yes i cannot access the admin panel at magento2.shop:6262/admin

Please correct me if I'm wrong but, since you set `MAGENTO_USE_SECURE_ADMIN=yes`, you must access the Admin Panel using https. In other words, you should be accessing Magento through https://magento2.shop:62443/admin instead of http://magento2.shop:6262/admin

**Comment by Fuseteam** [comment]
yes i did try and access it with https://magento2.shop:62443/admin, pardon the typo

**Comment by juan131** [comment]
Hi @Fuseteam 

I was able to reproduce the issue. It seems it's something that other users reported previously, you can find some workarounds provided in the issue below:

- https://github.com/bitnami/bitnami-docker-magento/issues/64

**Comment by Fuseteam** [comment]
that seems to be about a redirect loop, i don't seem to have a redirect loop. from what i can tell it just plain doesn't find admin the admin folder due to the added port

**Comment by juan131** [comment]
Hi @Fuseteam 

Correct. It seems there are two issues:

- When you modify the default HTTPS port, it cannot find the admin folder.
- When you use the default HTTPS port, it enters into a redirect loop when accessing the admin panel.

There is an internal task to address both issues, and I collected all the information so it's properly analyzed.

**Comment by Fuseteam** [comment]
@juan131 for what it is worth if i use the default port i do not get into a redirect loop, I only have the first issue you mention

**Comment by Fuseteam** [comment]
comment to remove stale label

**Comment by juan131** [comment]
Adding "on-hold" label to avoid the effect of "stale bot"

**Comment by marcosbc** [comment]
Hi @Fuseteam, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

In particular, this release now includes the new `MAGENTO_EXTERNAL_HTTP_PORT_NUMBER` and `MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER` environment variables, which you can use to achieve your purpose.

**Comment by Fuseteam** [comment]
thanks @marcosbc , i'll try it out when I can :+1:

**Comment by juan131** [comment]
Thanks @Fuseteam !! We'll keep this issue opened until you confirm us the results.
