### ISSUE TITLE
Correct way to install Extensions via Composer

### ISSUE THREAD

**Issue by hle-skillz** [bitnami/bitnami-docker-magento#168]
I've read Bitnami's [Install an extension using Composer](https://docs.bitnami.com/aws/apps/magento/configuration/install-extension-composer/) but it's unclear how to adapt it to Magento under docker.

Between the Readme sections [Upgrade this Application](https://github.com/bitnami/bitnami-docker-magento#upgrade-this-application) and [Extend this image](https://github.com/bitnami/bitnami-docker-magento#extend-this-image), I can't tell if the [standard CLI procedure](https://devdocs.magento.com/extensions/install/):
```
composer require <component-name>:<version>
bin/magento module:enable <component-name>
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:clean
```

should be performed as `RUN`s or as the final [CMD](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/Dockerfile#L67) in the `Dockerfile`.  Specifically, since Composer extensions are common across all horizontally scaled containers of the Magento service are they meant to live in the cached image layer or in the persistent volume?

**Comment by javsalgar** [comment]
Hi,

If you plan to add an extension, I'd say that adding it in the image build process makes sense, so all the instances have the same plugins. Did you find any issues with that?

**Comment by hle-skillz** [comment]
I hadn't tried either approach yet, just hit a conceptual wall when reading the [Upgrade this application](https://github.com/bitnami/bitnami-docker-magento#upgrade-this-application) instructions to pull the `latest` image and rsync-ing the volume.  That seems to imply all customizations (settings + extensions) were expected to be in the volume and not the image `Dockerfile`.  Unless "pull latest image" also meant "or update your image `FROM` statement".

**Comment by javsalgar** [comment]
Hi,

The customizations will be in the volume after the first initialization. That means that, during the installation logic, the configuration code will be move them to the persistent volume. If you add any extra customizations using, for example, the Magento Module manager, they will be persisted too. However, in your use case it makes more sense to be at docker build time.

**Comment by hle-skillz** [comment]
Does that mean only the step that pulls down the extension should be in the Dockerfile?
```
composer require <component-name>:<version>
```

specifically does the Magento architecture allow the remaining setup commands to make database calls or write to the configuration (effects that won't be properly captured by the image layers)?
```
bin/magento module:enable <component-name>
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:clean
```

**Comment by javsalgar** [comment]
I'm sure that the composer should work without issues, though I'm not sure about the magento commands, these may rely on the database. These last commands should be run at runtime, rather than when building the image. We are currently working on transitioning the container to a bash-based logic. Would it make sense for you to allow custom init scripts that would complete any missing installation step?

**Comment by hle-skillz** [comment]
Looks like the images currently have init scripts (for initializing the database) that requires the use of Persistent Volumes to prevent re-initialization on upgrades.  This runtime portion seems to require careful coordination if there are multiple containers being used for horizontal scaling of the app image.  Is it inconsistent when those Magento setup commands modify the container vs the database? trying to understand if a single task / hook container can be used to run the initialization commands separate from the app containers.

**Comment by javsalgar** [comment]
>  Is it hard to predict when those Magento setup commands modify the container vs the database?

Honestly, I'm not sure. I think the only way to know is to ask the Magento developers or to check the source code. I would check your exact use case and the commands you require.

**Comment by hle-skillz** [comment]
For the commands that will touch the database, the current [run-once file check](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/post-init.sh#L11) only works for persistent volumes and doesn't address multiple containers.  Does Bitnami have a recommended approach for k8s (init containers, hooks) to avoid clashes if multiple instances are started for horizontal auto scaling?

**Comment by javsalgar** [comment]
Hi,

Right now, for multiple instances, the only way that would work with our helm chart is using a ReadWriteMany PVC (for example, using nfs-provisioner). That means that all instances would share the same volume. In this sense, my advice would be to only set the init scripts in one of the pods.
