### ISSUE TITLE
Magento bitnami/magento:2.3.3-ol-7-r113 issue

### ISSUE THREAD

**Issue by mehrdadhosseinzadeh** [bitnami/bitnami-docker-magento#171]
hi to all
i am using magento bitnami/magento:2.3.3-ol-7-r113 and extended it

but i have error after docker-compose up -d --build

1 exception(s):
Exception #0 (ReflectionException): Class Magento\Catalog\Model\Category\Attribute\Backend\LayoutUpdate does not exist

my docker-compose file is 

version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: 'magento_mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_DATABASE=magento
    volumes:
      - 'mariadb_data:/bitnami'
  magento:
    container_name: 'magento_app'
    build: 
      context: ./Docker/app
      args:
        - GIT_USER=cicd
        - GIT_TOKEN=test
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_USERNAME=test
      - MAGENTO_PASSWORD=magento2021
      - MAGENTO_EMAIL=info@test.com
#      - MAGENTO_HOST=192.168.1.158
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - NAMI_DEBUG=1
      #sudo sysctl -w vm.max_map_count=262144
      #sudo sysctl -w fs.file-max=65536
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./local/magento_data:/bitnami
#    command: '/opt/bitnamic/magento/htdocs/rebuild'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    container_name: 'magento_elasticsearch'
    environment:
      - ELASTICSEARCH_PLUGINS:analysis-icu,analysis-phonetic2
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    mem_limit: 1024m

volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local

**Comment by alemorcuq** [comment]
Hi, @mehrdadhosseinzadeh. I've just tested the `bitnami/magento:2.3.3-ol-7-r113` image and it works properly, so the error is most likely related to your changes to the image. Can you check that?

**Comment by marcosbc** [comment]
Hi @mehrdadhosseinzadeh, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

If you are using the latest container image you should be able to easily extend it by modifying any of the initialization scripts.
