### ISSUE TITLE
change bitnami logo with out company logo

### ISSUE THREAD

**Issue by mehrdadhosseinzadeh** [bitnami/bitnami-docker-magento#172]
i am use magento bitnami docker image
on startup show bitnami logo in address : http://127.0.0.1/img/white_bitnami.png

how can i change it with custom image logo ?

**Comment by FraPazGal** [comment]
Hello @mehrdadhosseinzadeh,

I deployed the container but couldn't find the bitnami logo in `http://127.0.0.1/img/white_bitnami.png`, there was only the default `page not found` of Magento. Does this logo appear deploying the current `docker-compose.yaml`?

**Comment by FraPazGal** [comment]
Hello @mehrdadhosseinzadeh,

Yes, it seems that way. In that case, you could try customising the container and removing the apache vhost or the `index.html` file. For more info on customising our images, please refer to our [README](https://github.com/bitnami/bitnami-docker-magento#customize-this-image).

**Comment by marcosbc** [comment]
Hi @mehrdadhosseinzadeh, note that we don't configure any logo within the Bitnami Docker image for Magento anymore. Could it be possible that you're using an old Docker image?

NOTE: We have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo. If you are using 2.4.x then no Bitnami logo should appear.
