### ISSUE TITLE
Install Magento in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-magento#175]
# Install Magento in IBM Cloud

Would you like to create your own e-commerce with Magento using the IBM Cloud? This documentation will guide you on how to install Magento on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105614491-ca469400-5d97-11eb-8f88-35aba84326b7.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105614500-d4689280-5d97-11eb-9720-7cec9de1bbf1.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105614505-db8fa080-5d97-11eb-9ca9-06000fec166f.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105614511-e2b6ae80-5d97-11eb-8835-4070a51f30ba.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105614518-e9452600-5d97-11eb-9d26-c3f30fd3a181.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105614520-f06c3400-5d97-11eb-8131-cb3ce6516b67.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105614527-f82bd880-5d97-11eb-9f3b-8627903064c4.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105614530-ffeb7d00-5d97-11eb-9d10-de2cef86e94f.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105614534-08dc4e80-5d98-11eb-82fd-0a0adf522c9b.PNG)

## Step 3: Install Magento

* Click on the search section at the top of the main page, type Magento, and click on it.

![magento1](https://user-images.githubusercontent.com/70336951/105614541-14c81080-5d98-11eb-98c4-f59f52f07cac.PNG)

* A new window opens, select the cluster and enter the name you want for the Magento workspace, in this case, it will be called _magento-example_; then, go to the bottom to find the workspace parameters.

You can modify the different installation parameters at the bottom. We will leave them by default except for the credentials Magento uses for its database and its application. You will need the first to access your database console and the second one to access your new Magento application. You can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/prestashop "here").

Make sure you set up correctly the email and password for the application in the _magentoEmail_ and _magentoPassword_ variables. 

![magento3](https://user-images.githubusercontent.com/70336951/105614548-214c6900-5d98-11eb-9d78-ea97797088e6.PNG)

![magento4](https://user-images.githubusercontent.com/70336951/105614550-24dff000-5d98-11eb-8757-acea4be2f168.PNG)

The admin user will be _root_ by default, and you can change its password in the _mariadb.auth.rootPassword_.

![magento5](https://user-images.githubusercontent.com/70336951/105614554-2a3d3a80-5d98-11eb-9020-74031e9d43ea.PNG)

When you're done, accept the terms, and click on *Install*.

![magento2](https://user-images.githubusercontent.com/70336951/105614556-30cbb200-5d98-11eb-9db7-c2e779109eb4.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test11](https://user-images.githubusercontent.com/70336951/105614578-4ccf5380-5d98-11eb-96df-3331fa65cfe6.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105614591-59ec4280-5d98-11eb-9692-ac1e2fb7e92c.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105614597-61abe700-5d98-11eb-8605-d1aa8cfdedc1.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105614602-68d2f500-5d98-11eb-95a4-d1244c0568b2.PNG)

* Once you have installed the terminal, open it, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *magento-example* is now active.

`$ kubectl get ns`

![testmagento1](https://user-images.githubusercontent.com/70336951/105614610-712b3000-5d98-11eb-8288-b2723aa06b85.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testmagento2](https://user-images.githubusercontent.com/70336951/105614612-76887a80-5d98-11eb-9684-887b467b488f.PNG)

* You can know enter the application and its sample website by accessing the External IP.

`$ kubectl get service -n NAME SERVICE`

![testmagento3](https://user-images.githubusercontent.com/70336951/105614615-7c7e5b80-5d98-11eb-9b67-e54d9a0b183b.PNG)

* Select the pod within your service using bash so you can start interacting with the Magento system files and console from the terminal.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testmagento4](https://user-images.githubusercontent.com/70336951/105614621-82743c80-5d98-11eb-974c-c037af1df857.PNG)

You have finished the installation, enjoy your Magento installation and start building your e-commerce!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
