### ISSUE TITLE
Switch to disable configurePermissions for /bitnami/magento

### ISSUE THREAD

**Issue by stijnbrouwers** [bitnami/bitnami-docker-magento#176]
**Description**

I am unable to run Magento using Azure Files as persistence storage for /bitnami/magento

**Describe the results you received:**

The Magento pod initialization is stuck (or takes extremely long) at this step:
```magento TRACE [configurePermissions] File to chown: /bitnami/magento```

**Describe the results you expected:**

Pod initialization to proceed past the point mentioned before.

**Additional information you deem important (e.g. issue happens only occasionally):**
The action for chowning is irrelevant for Azure Files.
When mounting the volume, you define the user and group ids that apply to the files contained in the volume.
Chowning the volume effectively tries changing the ownership of all files which is really slow. In the end, since guid and uid are set during mount, the chown command doesn't actually change the permissions (it's ignored). So it would be great if we can just skip this step for example by using an environment variable in the deployment's definition SKIP_MAGENTO_VOLUME_PERMISSIONCONFIGURATION or something like that...

Source for using Azure Files: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume

**Version**
- Helm chart: 8.3.6

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AKS

**Comment by carrodher** [comment]
The bitnami/magento 8.3.6 Helm Chart is quite old, from that version until now several major changes have been implemented in the Helm Chart and in the container image. Can you try using the latest version?
