### ISSUE TITLE
Run container without redis and elastic

### ISSUE THREAD

**Issue by BartoszCoyote** [bitnami/bitnami-docker-magento#178]
Hello,

Is there any way to run a container without redis and elasticsearch?
I need magento just for test purpose and do not want to run heavy containers.

**Comment by andresbono** [comment]
Hi @BartoszCoyote, `redis` is not being used but `elasticsearch` must be configured in Magento `2.4`, see https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html. It enables some core features for an e-commerce.

Maybe you can try to launch first all the containers, once the firstboot finishes, deactivate elasticsearch from Magento and then stop the elasticsearch container. I don't even know if that is possible, but maybe it's worth trying.

**Comment by BartoszCoyote** [comment]
Ok, but now i have a problem with install with no information about error.
![image](https://user-images.githubusercontent.com/4238723/107031415-6fa73200-67b2-11eb-80cc-83cf87ab2ae8.png)

And process restarting..

**Comment by andresbono** [comment]
You can try to add the `BITNAMI_DEBUG=true` environment variable in the Magento container. It should show more information about the issue.

**Comment by BartoszCoyote** [comment]
@andresbono 
![Uploading image.png…]()

**Comment by andresbono** [comment]
Hi @BartoszCoyote, I couldn't find that issue when try to reproduce it on my side. Can you share your docker-compose?
