### ISSUE TITLE
Magento Docker Container stops running at "Running Magento Install Script"

### ISSUE THREAD

**Issue by stousmand** [bitnami/bitnami-docker-magento#183]
I came across this while I was attempting to set up a Magento Docker environment for learning purposes. My objective is to find out if there are REST API's or other APIs provided by Magento so that I could integrate my custom application with Magento and how to do it. In order to do so the best way I felt was to setup a Docker environment.

Steps followed :
1) I followed instructions in mentioned [here](https://github.com/bitnami/bitnami-docker-magento), under "Using the Docker Command Line"
2) Started MariaDB
```
docker run -d --name mariadb -p 3306:3306 --env ALLOW_EMPTY_PASSWORD=yes --env MARIADB_USER=bn_magento --env MARIADB_PASSWORD=bitnami --env MARIADB_DATABASE=bitnami_magento --network magento-network --volume mariadb_data:/bitnami/mariadb bitnami/mariadb:latest
```
3) Started Elasticsearch
```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" --network magento-network docker.elastic.co/elasticsearch/elasticsearch:7.10.2
```
4) Started Magento
```
docker run -d --name magento -p 8080:8080 -p 8443:8443 --env ALLOW_EMPTY_PASSWORD=yes --env MAGENTO_DATABASE_USER=bn_magento --env MAGENTO_DATABASE_PASSWORD=bitnami --env MAGENTO_DATABASE_NAME=bitnami_magento --env MAGENTO_ELASTICSEARCH_HOST=172.18.0.3 --network magento-network --volume magento_data:/bitnami/magento -it bitnami/magento:latest
```
MariaDB and Elasticsearch containers run without any issues but the Magento container runs for a while and it stops.
![image](https://user-images.githubusercontent.com/29155859/108955815-c8246d80-7694-11eb-9b5f-20356a0836a4.png)

I'm running Docker in Windows 10 and my Docker version is 
![image](https://user-images.githubusercontent.com/29155859/108956198-5e589380-7695-11eb-8983-2bad27c34993.png)

When I checked the logs in Docker Desktop client it showed this,
![image](https://user-images.githubusercontent.com/29155859/108956365-8b0cab00-7695-11eb-9a40-4e7b95d9ec8e.png)

As seen in the console it stops from "Running Magento Install Script".

I'm not sure why this happens, and I do not know a way to troubleshoot this. Any clue on how I could solve this and get a container up and running. Thanks

**Comment by Mauraza** [comment]
Hi @stousmand,

Did you try with the docker-compose?
```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

**Comment by stousmand** [comment]
Hi @Mauraza, yeah I did and came across an issue which I cannot remember so I thought of running the containers individually as mentioned in the second option. Gave more control. The thing is, I cannot identify what the issue is, the container just stops from that log line.

**Comment by stousmand** [comment]
@Mauraza I thought the latest image might have an issue so I used the Magento image (docker.io/bitnami/magento:2-debian-10) in docker-compose.yml file and executed as mentioned above got the same result as before.

**Comment by Mauraza** [comment]
Hi @stousmand, 

I found the problem, it's the version of MariaDB, could you try with the following commands?

```
docker network create magento-network
docker volume create --name mariadb_data
docker run -d --name mariadb --env ALLOW_EMPTY_PASSWORD=yes --env MARIADB_USER=bn_magento --env MARIADB_DATABASE=bitnami_magento --env MARIADB_PASSWORD=bitnami --network magento-network --volume mariadb_data:/bitnami/mariadb bitnami/mariadb:10.3-debian-10
docker run -d --name elasticsearch --network magento-network  bitnami/elasticsearch:latest
docker run -d --name magento -p 8080:8080 -p 8443:8443 --env MAGENTO_HOST=localhost --env ALLOW_EMPTY_PASSWORD=yes --env MAGENTO_DATABASE_USER=bn_magento --env MAGENTO_DATABASE_PASSWORD=bitnami --env MAGENTO_DATABASE_NAME=bitnami_magento  --network magento-network --volume magento_data:/bitnami/magento bitnami/magento:2-debian-10 
```
I hope that helps you.

**Comment by stousmand** [comment]
Hi @Mauraza, let me give it a shot. Thanks for the help.

**Comment by Mauraza** [comment]
Hi @stousmand, 

Did it work for you? or have you had any other type of problem?

**Comment by stousmand** [comment]
@Mauraza Yes it worked, the container is running it didnt stop. Thanks for the help. But I faced another issue which I think is not directly related to this. The Magento initial page does not load any CSS (that is what I think because there are no styles applied once accessing http://localhost:80, didnt inspect through browser developer tools yet).
