### ISSUE TITLE
PHP OPcache revalidation configuration

### ISSUE THREAD

**Issue by gowrizrh** [bitnami/bitnami-docker-magento#187]
**Description**
I've setup an environment as a playground to test and isolate Magento things in. There's an issue where the file changes aren't being picked up. I've created a GraphQL resolver and it works fine for the first time but as soon as you make any changes to that file, it is not picked up and still somehow uses the old file.  Restarting the containers seem to pick up that change but only for that one time, any subsequent changes require corresponding container restarts. This sounds like an opcache issue. I believe this happens specifically is in the area of code that will be code generated by Magento that is anything that goes in `generated` like a plugin interceptor.

**Steps to reproduce the issue:**

1. `docker-compose up -d` this environment.
2. Mount host directories as data volumes with Docker Compose
3. Create a new module, a new query in a graphql schemafile and a resolver
4. Run the GraphQL query. (Works fine at this stage)
5. Make modifications to your resolver file
6. Run the GraphQL query

**Describe the results you received:**

The response is from a previous 'version' of the file

**Describe the results you expected:**

Any modifications to the file should have been picked up automatically

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 20.10.5, build 55c4c88
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-44-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.35GiB
 Name: sayyadina
 ID: MQQ6:QQKO:KHU2:X24P:7ZNH:5C3R:76GS:JPIB:KNM3:EQL6:QC6Y:ZL5Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.5, build c4eb3a1f
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
The file mounted inside the container should be modified when you perform some changes in the "same" file from your host, for example:

- I added the following line to the volumes section present in the _docker-compose.yaml_ from this repo:
```yaml
     volumes:
       - 'magento_data:/bitnami/magento'
       - '/home/bitnami/bitnami-docker-magento/myfile.txt:/opt/bitnami/myfile.txt'
```

- Being the content of _myfile.txt_ in the host machine:
```console
$ cat myfile.txt
Hi
```

- I deployed the docker-compose:
```console
$ docker-compose up -d
```

- Checking the mounted file:
```console
$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS          PORTS                                         NAMES
20f0d05a1cb0   bitnami/magento:2-debian-10         "/opt/bitnami/script…"   44 seconds ago   Up 42 seconds   0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitnami-docker-magento_magento_1
a5f47c71a915   bitnami/elasticsearch:6-debian-10   "/opt/bitnami/script…"   46 seconds ago   Up 44 seconds   9200/tcp, 9300/tcp                            bitnami-docker-magento_elasticsearch_1
f879df18452b   bitnami/mariadb:10.3-debian-10      "/opt/bitnami/script…"   46 seconds ago   Up 43 seconds   3306/tcp                                      bitnami-docker-magento_mariadb_1

$ docker exec -it 20f0d05a1cb0 cat /opt/bitnami/myfile.txt
Hi
```

- Then, I modified it in the host (different console tab):
```console
$ vim myfile.txt
$ cat myfile.txt
Bye
```

- Doing the same check in the container, the file was modified accordingly:
```console
$ docker exec -it 20f0d05a1cb0 cat /opt/bitnami/myfile.txt
Bye
```
-----------------------------------------------------
Something similar can be done but using a directory instead of a file:
- I added the following line to the volumes section present in the _docker-compose.yaml_ from this repo:
```yaml
     volumes:
       - 'magento_data:/bitnami/magento'
       - '/home/bitnami/bitnami-docker-magento/directory:/opt/bitnami/directory'
```

- I deployed the docker-compose:
```console
$ docker-compose up -d
```

- Checking the mounted directory:
```console
$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS          PORTS                                         NAMES
b54ddbdec13f   bitnami/magento:2-debian-10         "/opt/bitnami/script…"   19 seconds ago   Up 18 seconds   0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitnami-docker-magento_magento_1
02b785858bb2   bitnami/mariadb:10.3-debian-10      "/opt/bitnami/script…"   22 seconds ago   Up 19 seconds   3306/tcp                                      bitnami-docker-magento_mariadb_1
38329e9bafdf   bitnami/elasticsearch:6-debian-10   "/opt/bitnami/script…"   22 seconds ago   Up 20 seconds   9200/tcp, 9300/tcp                            bitnami-docker-magento_elasticsearch_1

$ docker exec -it b54ddbdec13f ls -la /opt/bitnami/
total 64
drwxrwxr-x 1 root   root 4096 Mar 19 08:50 .
drwxrwxr-x 1 root   root 4096 Mar 18 20:23 ..
-rw-r--r-- 1 root   root 1770 Mar 18 20:23 .bitnami_components.json
drwxrwxr-x 1 root   root 4096 Mar 18 20:23 apache
lrwxrwxrwx 1 root   root    6 Mar 18 20:24 apache2 -> apache
drwxr-xr-x 1 root   root 4096 Sep 29 19:10 common
drwxrwxr-x 2   1000 1000 4096 Mar 19 08:50 directory
drwxrwxr-x 2 root   root 4096 Mar 18 20:23 licenses
drwxrwxr-x 1 daemon root 4096 Mar 18 20:28 magento
drwxr-xr-x 1 root   root 4096 Mar 18 20:28 mysql
drwxr-xr-x 1 root   root 4096 Mar 17 12:12 php
drwxrwxr-x 1 root   root 4096 Mar 18 20:23 scripts

$ docker exec -it b54ddbdec13f ls -la /opt/bitnami/directory
total 12
drwxrwxr-x 2 1000 1000 4096 Mar 19 08:50 .
drwxrwxr-x 1 root root 4096 Mar 19 08:50 ..
```

- Then, I moved the previous file inside the directory in the host:
```console
$ mv myfile.txt directory
```

- Checking that those changes are bein taken into account when working with directories:
```console
$ docker exec -it b54ddbdec13f ls -la /opt/bitnami/directory
total 16
drwxrwxr-x 2 1000 1000 4096 Mar 19 08:53 .
drwxrwxr-x 1 root root 4096 Mar 19 08:53 ..
-rw-rw-r-- 1 1000 1000    4 Mar 19 08:37 petete.txt
```
-----------------------------------------------------
Can you do something similar to check if the files/dir are being modified inside the container? Are you mounting them in a different way?

If the changes are applied inside the container, then maybe it is something related to how the application itself uses those files, probably changes are not being taken into account until the service or process is restarted so although the last version of the file is properly mounted into the container, it is not going to be used by the application itself

**Comment by gowrizrh** [comment]
Yes... the issue I believe is OPCache kicking in and not invalidating the compiled script bytecodes.

**Comment by gowrizrh** [comment]
I've had some time to dig deeper into this and it turns out that it was indeed opcache kicking in. I was able to solve my issue by tweaking a couple of opcache settings and restarting apache.

Here's the tiny changes I made to my `php.ini`
```
opcache.validate_timestamps = 1

opcache.revalidate_freq = 0
```

However, I've found out there's another issue.

After modifying your `php.ini` settings, trying to restart apache using the scripts provided at `/opt/bitnami/scripts/apache/stop.sh` exits with error code 137.

For the time being, I've just restarted apache with `/opt/bitnami/apache/bin/httpd -k restart`

I've also noticed `/opt/bitnami/apache/bin/httpd -k stop` results in container exiting with error code 137.

**Comment by carrodher** [comment]
The apache process is the main process attached to the container if this process is killed (or restarted) the container will die in the same way:
```
root@72c5b7322725:/# ps xufa
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         250  0.0  0.0   3996  3260 pts/0    Ss   07:58   0:00 bash
root         320  0.0  0.0   7640  2740 pts/0    R+   08:00   0:00  \_ ps xufa
root           1  0.0  0.1 624284 39036 ?        Ss   07:57   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
root         278  0.0  0.0   5512  2060 ?        Ss   07:59   0:00 /usr/sbin/cron
root         287  0.0  0.0   6056  2036 ?        S    08:00   0:00  \_ /usr/sbin/CRON
daemon       288  0.0  0.0   2388   696 ?        Ss   08:00   0:00      \_ /bin/sh -c /opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/bitnami/magento/var/log/magento.cron.log
daemon       289 50.6  0.5 776036 177816 ?       S    08:00   0:10          \_ /opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cron:run
daemon       290  0.0  0.0   3084   824 ?        S    08:00   0:00          \_ grep -v Ran jobs by schedule
daemon       282  0.0  0.0 624284  8636 ?        S    07:59   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
daemon       283  0.0  0.0 624284  8636 ?        S    07:59   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
daemon       284  0.0  0.0 624284  8636 ?        S    07:59   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
daemon       285  0.0  0.0 624284  8636 ?        S    07:59   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
daemon       286  0.0  0.0 624284  8636 ?        S    07:59   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
daemon       303 15.7  0.3 657000 93388 ?        D    08:00   0:01 /opt/bitnami/php/bin/php /bitnami/magento/bin/magento cron:run --group=ddg_automation_main --bootstrap=standaloneProcessStarted=1
daemon       309 14.6  0.2 648804 84940 ?        D    08:00   0:01 /opt/bitnami/php/bin/php /bitnami/magento/bin/magento cron:run --group=yotpo_yotpo --bootstrap=standaloneProcessStarted=1

root@72c5b7322725:/# /opt/bitnami/apache/bin/httpd -k stop
Terminated
```

Maybe you can place the desired code in the persisted volume so you can restart the container (and with that the different processes) without losing the data. https://github.com/bitnami/bitnami-docker-magento#persisting-your-application
