### ISSUE TITLE
Backup and restore, permissions issues

### ISSUE THREAD

**Issue by h-tx** [bitnami/bitnami-docker-magento#188]
Basically, I need to backup and restore a magento website deployed with docker-compose.

This is my `docker-compose.yml`
```
version: "3"
services:
  mariadb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    container_name: $DB_CONTAINER
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=$DB_USER
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_PASSWORD=$DB_PASSWORD
    volumes:
      - "./mariadb_data:/bitnami"

  magento:
    image: "docker.io/bitnami/magento:2.4.1-debian-10-r72"
    environment:
      - MARIADB_HOST=$DB_CONTAINER
      - MARIADB_PORT_NUMBER=$DB_PORT
      - MAGENTO_DATABASE_USER=$DB_USER
      - MAGENTO_DATABASE_PASSWORD=$DB_PASSWORD
      - MAGENTO_DATABASE_NAME=$DB_NAME
      - MAGENTO_USERNAME=$DB_USER
      - MAGENTO_PASSWORD=$DB_PASSWORD
      - MAGENTO_ADMINURI=$DB_USER
      - MAGENTO_MODE=developer
      - MAGENTO_HOST=$MAGENTO_HOSTNAME
      - MAGENTO_USE_SECURE_ADMIN=yes
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_CONTAINER
      - ELASTICSEARCH_PORT_NUMBER=9200
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$SITE_HOSTNAME
      - LETSENCRYPT_EMAIL=$SITE_EMAIL
    volumes:
      - "./magento_data:/bitnami"
      - "./themes:/themes"
    depends_on:
      - mariadb
      - elasticsearch
    ports:
      - $CONTAINER_PORT:80
      - $CONTAINER_SSL_PORT:443

  elasticsearch:
    image: "docker.io/bitnami/elasticsearch:7-debian-10"
    container_name: $ELASTICSEARCH_CONTAINER
    volumes:
      - "./elasticsearch_data:/bitnami/elasticsearch/data"

networks:
  default:
    external:
      name: nginx_proxy

volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local
```

My site is working fine, but for some reason I cannot backup and restore the volumes in a different host (I need the database, images, configurations, etc)

I tried to `rsync` the `/var/lib/docker/volumes`, then `docker-compose up -d` and all the containers except the magento one crash without being able to log in and fix the issue (maybe chowning could work), for example, elastic search throws:
```
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/bitnami/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
        at java.base/java.nio.file.Files.createDirectories(Files.java:783)
        at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:275)
        at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:212)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:272)
        at org.elasticsearch.node.Node.<init>(Node.java:362)
        at org.elasticsearch.node.Node.<init>(Node.java:289)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /opt/bitnami/elasticsearch/logs/elasticsearch.log
```

So I think I probably need to change some paths, I would rather avoid having to extend the image, and I don't know the quickest way to backup/restore a magento deployment with database & elasticsearch.

Any ideas are welcome.

**Comment by marcosbc** [comment]
Hi @h-tx, it could be that you are not preserving files ownership/permissions when copying over to the new volume.

In any case I'd not recommend to `rsync` the `/var/lib/docker` directory. Instead, I'd advise to follow these steps to backup and restore the persistent data for all nodes: https://github.com/bitnami/bitnami-docker-magento#backing-up-your-container

You would need to run that command for each of the volumes, and then mounting the backup directories as shown here: https://github.com/bitnami/bitnami-docker-magento#restoring-a-backup

Hope it helps!

**Comment by adampwright** [comment]
@marcosbc Looking for clarification on this please, as I feel the link https://github.com/bitnami/bitnami-docker-magento#backing-up-your-container you gave is offering incomplete/vague information. 

I currently have a backup of locally persisted data, made with a simple sudo cp to /backups in the same directory as the docker-compose. 

I run the command listed:

`$ docker run --rm -v /backups/magento:/backups --volumes-from magento busybox \
  cp -a /bitnami/magento /backups/latest
`

It runs for a bit, yet nothing happens and I can see no files that are created. 

Can you elaborate please? 

Here is my docker-compose:

`version: '2'
services:
  mariadb:
    user: root
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=hidden
      - MARIADB_DATABASE=hidden
    volumes:
      - ./mariadb:/bitnami/mariadb
  magento:
    user: root
    image: 'docker.io/bitnami/magento:2-debian-10'
    container_name: magento
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=ecom
      - MAGENTO_DATABASE_NAME=ecom
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_MEMORY_LIMIT=-1
      - MAGENTO_USERNAME=hidden
      - MAGENTO_PASSWORD=hidden
      - MAGENTO_EMAIL=hidden
      - MAGENTO_MODE=developer
    volumes:
      - ./magento:/bitnami/magento

    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    user: root
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    container_name: elasticsearch
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  # mariadb_data:
  #   driver: local
  # magento_data:
  #   driver: local
  elasticsearch_data:
    driver: local`

**Comment by marcosbc** [comment]
Hi @adampwright, it works fine for me. For instance, if I deploy the `docker-compose.yml` in a folder called `mag` then command could look like this:

```console
$ docker run --rm -v $(pwd)/mage-backups:/backups --volumes-from mag_magento_1 busybox \
  cp -a /bitnami/magento /backups/latest
```

(note that you must replace the path to the backup directory in `-v` and the docker container name in `--volumes-from`)

Then, after it completes, I can see the contents in the `mage-backups` folder:

```console
$ ls mage-backups/latest
app               CHANGELOG.md   COPYING.txt  grunt-config.json.sample  LICENSE_AFL.txt  nginx.conf.sample    pub          tmp      vendor
auth.json.sample  composer.json  dev          Gruntfile.js.sample       licenses         package.json.sample  SECURITY.md  uploads
bin               composer.lock  generated    lib                       LICENSE.txt      phpserver            setup        var
```

Also note that, to backup everything, you need to follow the same process for both MariaDB and Elasticsearch.

**Comment by adampwright** [comment]
@marcosbc This worked thank you! Not sure what I was doing wrong before, but your command with my own edits fixed it. Might have forgotten to stop the containers beforehand. Perhaps had an effect, perhaps not.

**Comment by octohedron** [comment]
Hello, I had the same issue and I realized I could make it work by setting up the volumes as @h-tx and @adampwright  (local) then stopping the containers and the backup would be simply creating a tar with the folders.
So, basically, with volumes as local, then
1. `docker-compose down`
2. `sudo tar -czvf backup.tar mariadb elasticsearch magento`

For restoring
1. `tar -xzvf backup.tar`
2. `sudo chown $(whoami):$(whoami) mariadb elasticsearch magento` (at your own risk)
3. `chmod 777 mariadb elasticsearch magento` (at your own risk)

The permissions were required for me, although you could probably try with something less permissive, and that's it, then `docker-compose up -d` with the same `docker-compose.yml` of course.

Only downside is having to do `docker-compose down`, (might be ok without it, haven't tested it) but it should be ok if you have multiple instances running with a load balancer, etc.
