### ISSUE TITLE
MariaDb 10.5 support

### ISSUE THREAD

**Issue by BartoszCoyote** [bitnami/bitnami-docker-magento#191]
I am trying to connect a database in version 10.5.
But unfortunately, magento doesn't support 10.5 yet and it doesn't look like this will change in the future.

I came up with the idea to change the database version in di.xml file.
But I have reached a wall and am unable to replace the contents of this file when building the image

Any ideas on how I can achieve this, or maybe you have another better idea

**Comment by alvneiayu** [comment]
hi @BartoszCoyote 

As you said, Magento doesn't support MariaDB 10.05. Therefore, we can not help you in this challenge. You can extend the image and you can try to do some changes but it is not officially supported and I think that you are going to have problems. Maybe, you can ask in [Magento Forum](https://community.magento.com/).

Sorry and thanks for your time

Álvaro
