### ISSUE TITLE
Scripts/styles/etc not being loaded from non-default port

### ISSUE THREAD

**Issue by mahgo** [bitnami/bitnami-docker-magento#192]
I'm using the docker compose file in this repository.

I'm wanting to change the port that I connect to on the docker host from the default of 80 to 8080, so I changed the following in my docker compose:

ports:
      - '8080:8080'
      - '8443:8443'

When connecting on localhost:8080, the page itself loads, but everything else like styles and scripts are attempted to be loaded over the default port (80) and therefore 404.

I've tried setting MAGENTO_EXTERNAL_HTTP_PORT_NUMBER, but that doesn't change anything.

**Comment by juan131** [comment]
Hi @mahgo 

Did you have persisted data from previous deployments in the volume attached to Magento? I was unable to reproduce the issue following these steps:

- Download the `docker-compose.yaml`:

```console
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
```

- Apply the changes below in the `docker-compose.yaml`:

```diff
version: '2'
services:
  (...)
  magento:
    (...)
    environment:
      - MAGENTO_HOST=localhost
+     - MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=8080
+     - MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER=8443
      - MAGENTO_DATABASE_HOST=mariadb
   (...)
```

- Launch the containers and wait for Magento to be ready:

```console
$ docker-compose up -d
$ docker-compose logs -f magento
(...)
magento_1  |
magento_1  | magento 13:25:35.12 INFO  ==> ** Magento setup finished! **
magento_1  | magento 13:25:35.14 INFO  ==> ** Starting cron **
magento_1  | magento 13:25:35.17 INFO  ==> ** Starting Apache **
(...)
```

- Open a browser and go to http://localhost:8080

![Screenshot 2021-05-14 at 15 28 14](https://user-images.githubusercontent.com/6740773/118277421-11809e00-b4c9-11eb-8760-1c6f1d574cbc.png)

**Comment by mahgo** [comment]
Looks like deleting all existing containers/volumes etc and re-creating it did the trick, thanks!
