### ISSUE TITLE
Issues building image using WSL 2

### ISSUE THREAD

**Issue by mahgo** [bitnami/bitnami-docker-magento#194]
**Description**
I'm using WSL2 (Ubuntu, Windows Terminal) and am trying to build the image using `docker build 2/debian-10/`. I'm getting this error on step 3:
```
 > [ 3/19] RUN install_packages acl ca-certificates cron curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsodium23 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libwebp6 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps tar zlib1g:
#8 0.664 /bin/sh: 1: install_packages: not found
```

Also, if I replace `install_packages` with `apt-get update -qq && apt-get install -y --no-install-recommends`, I then get stuck on step 4:
```
> [ 4/19] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7:
: not foundin/sh: 4: /opt/bitnami/scripts/libcomponent.sh:
: not foundin/sh: 8: /opt/bitnami/scripts/libcomponent.sh:
: not foundin/sh: 10: /opt/bitnami/scripts/libcomponent.sh:
#8 0.315 /bin/sh: 24: /opt/bitnami/scripts/libcomponent.sh: 1: name is required
------
executor failed running [/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7]: exit code: 2
```

Is there something I'm missing re building this image?

**Steps to reproduce the issue:**

1. Clone repo
2. `docker build 2/debian-10/`

**Describe the results you received:**

See above errors.

**Describe the results you expected:**

Image successfully building

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 38
  Running: 36
  Paused: 0
  Stopped: 2
 Images: 118
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 25.01GiB
 Name: docker-desktop
 ID: RYX5:SKMN:LZQM:QSCK:B2TF:U5CZ:LKGU:6DCL:SFMX:AACC:HKU2:GXW4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 144
  Goroutines: 126
  System Time: 2021-06-07T02:31:54.6499334Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by alvneiayu** [comment]
hi @mahgo 

Could you share with me the content inside the 2/debian-10, please?

```
ls -la 2/debian-10
```

Moreover, could you share me also the content inside the rootfs and the prebuildfs, please?

Thanks

Álvaro

**Comment by mahgo** [comment]
Sure.

debian-10: `Dockerfile  docker-compose.yml  prebuildfs  rootfs`
rootfs: `opt  post-init.d  post-init.sh`
prebuildfs: `opt  usr`

**Comment by alvneiayu** [comment]
hi @mahgo 

I am going to try to reproduce your problem. Did you change something in the repository?

Thanks and sorry for the late reply.

Álvaro

**Comment by mahgo** [comment]
Hi @alvneiayu,

No I did not, I wanted to get it working first.

**Comment by alvneiayu** [comment]
hi @mahgo 

I don't have experience with WSL but taking a look the scripts, the line that you are having problems:
```
 24     local name="${1:?name is required}"
```
It seems that it is not receiving the parameter as expected. The Dockerfile seems that it is ok

```
> [ 4/19] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7:
```

It is something really strange. Could you modify your Dockerfile to do something like:
```
source /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7
```
Just to do a test using directly the source command.

I am using Ubuntu and I can not reproduce the problem. So I think that it is something with the WSL2 environment.

Thanks a lot for your help and your time

Álvaro

**Comment by mahgo** [comment]
Hi @alvneiayu,

Do you mean to have a RUN in front of that source? Without it, I get `failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 12: unknown instruction: SOURCE`

With it, I get this error:
```
 => ERROR [ 4/19] RUN SOURCE /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum  0.3s
------
 > [ 4/19] RUN SOURCE /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7:
#8 0.248 /bin/sh: 1: SOURCE: not found
------
executor failed running [/bin/sh -c SOURCE /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.4.20-0" --checksum 35fb8a14f2f1b2d6f1b5ee01b0c60663522effe870a5c97c8a298450b68083e7]: exit code: 127
```

**Comment by mahgo** [comment]
Looks like it's also an issue when building out of WSL2 (in Powershell instead of Ubuntu WSL2 bash), in case that means anything.

**Comment by alvneiayu** [comment]
hi @mahgo 

I think that this is a problem with WSL2. Do you have any option to try to execute it in the same computer with a bash terminal? In a Linux installer or live cd.

Thanks a lot

Álvaro

**Comment by mahgo** [comment]
Hi @alvneiayu,

I managed to get it working in an Ubuntu VM.

Would it be possible getting this working in WSL2 as well? Maybe there are extra steps to setting up one's WSL2 environment?

**Comment by alvneiayu** [comment]
hi @mahgo 

I created an internal task to investigate and decide the best option to fix the problem and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot for reporting the problem and for your time.

Álvaro

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
