### ISSUE TITLE
Edit env.php

### ISSUE THREAD

**Issue by BartoszCoyote** [bitnami/bitnami-docker-magento#196]
I need to edit env.php while initialize.
I tried to edit file in libmagento.sh file but the file is not yet created.

How can I do it differently

**Comment by rafariossaa** [comment]
Hi,
  Not very sure what you want to change in the file and if it is needed for in the initialization of for the run.
  Maybe you can use the `run.sh` [before apache is started](https://github.com/bitnami/bitnami-docker-magento/blob/68bec0676af079d6d010c7a35789ccc760208917/2/debian-10/rootfs/opt/bitnami/scripts/magento/run.sh#L39).

**Comment by BartoszCoyote** [comment]
i need to add entry to `driver_options`

**Comment by BartoszCoyote** [comment]
@rafariossaa  i need to add `PDO::MYSQL_ATTR_SSL_CA ` because my db provider require ssl with ca file.

**Comment by BartoszCoyote** [comment]
@rafariossaa any helpful ideas?

**Comment by rafariossaa** [comment]
Hi,
  To enable SSL in the database connection you have several environment variables. Could you take a look to [these settings](https://github.com/bitnami/bitnami-docker-magento#user-content-database-server-connection-credentials-and-configuration) ?
