### ISSUE TITLE
ElasticSearch won't startup due to service resolution issue

### ISSUE THREAD

**Issue by huzaynbolt** [bitnami/bitnami-docker-magento#197]
**Description**

Magento refuse to start due to a name resolution issue with Elasticsearch instance

**Steps to reproduce the issue:**

1. Run the Docker compose file with elastic search configure

**Describe the results you received:**

The Magento instance refuses to start due to failure while resolving the Elastic search instance

**Describe the results you expected:**

The instance should resolve Elasticsearch via  the service name successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Logs
`mariadb_magento_1  | mariadb 17:51:07.14 INFO  ==> ** MariaDB setup finished! **
mariadb_magento_1  |
mariadb_magento_1  | mariadb 17:51:07.23 INFO  ==> ** Starting MariaDB **
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.29-MariaDB) starting as process 1 ...
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Using Linux native AIO
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Uses event mutexes
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Number of pools: 1
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128Mmariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Waiting for purge to start
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: 10.3.29 started; log sequence number 1625693; transaction id 20
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] InnoDB: Buffer pool(s) load completed at 210624 17:51:07
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Warning] 'proxies_priv' entry '@% root@a6bf19c777ea' ignored in --skip-name-resolve mode.
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] Reading of all Master_info entries succeeded
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] Added new Master_info '' to hash table
mariadb_magento_1  | 2021-06-24 17:51:07 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_magento_1  | Version: '10.3.29-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
magento_1          | magento 17:51:11.53 DEBUG ==> Executing SQL command:
magento_1          | SELECT 1
magento_1          | 1
magento_1          | magento 17:51:11.55 INFO  ==> Trying to connect to Elasticsearch
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | magento 17:52:11.68 ERROR ==> Could not connect to Elasticsearch
docker_magento_1 exited with code 1`

Compose File

```
version: '2'
services:
  mariadb_magento:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '8082:8080'
    environment:
      - MAGENTO_HOST=xx.yy.zz.cc
      - MAGENTO_DATABASE_HOST=mariadb_magento
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
      - MAGENTO_ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_ELASTICSEARCH_PORT_NUMBER=9200
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb_magento
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:6
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Ubuntu

**Comment by alvneiayu** [comment]
hi @huzaynbolt 

Could you share with me docker-compose logs of the elasticsearch container, please?

Just to verify that it is running properly.

Thanks a lot

Álvaro

**Comment by huzaynbolt** [comment]
Hi @alvneiayu, This is the logs on the Elastic container. The container exited itself without giving any reason over a while.

`ubuntu@ip-172-31-25-186:~$ sudo docker logs 978
elasticsearch 17:12:46.11
elasticsearch 17:12:46.14 Welcome to the Bitnami elasticsearch container
elasticsearch 17:12:46.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 17:12:46.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 17:12:46.16
elasticsearch 17:12:46.17 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:12:46.30 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:12:46.43 INFO  ==> Setting default configuration
elasticsearch 17:12:46.59 INFO  ==> Configuring Elasticsearch cluster settings...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch 17:19:44.07
elasticsearch 17:19:44.08 Welcome to the Bitnami elasticsearch container
elasticsearch 17:19:44.09 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 17:19:44.10 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 17:19:44.10
elasticsearch 17:19:44.12 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:19:44.18 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:19:44.24 INFO  ==> Custom configuration file detected, using it...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch 17:30:24.40
elasticsearch 17:30:24.41 Welcome to the Bitnami elasticsearch container
elasticsearch 17:30:24.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 17:30:24.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 17:30:24.43
elasticsearch 17:30:24.43 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:30:24.49 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:30:24.58 INFO  ==> Custom configuration file detected, using it...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch 17:49:13.51
elasticsearch 17:49:13.51 Welcome to the Bitnami elasticsearch container
elasticsearch 17:49:13.52 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 17:49:13.52 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 17:49:13.54
elasticsearch 17:49:13.54 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:49:13.65 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:49:13.75 INFO  ==> Custom configuration file detected, using it...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch 17:50:55.45
elasticsearch 17:50:55.46 Welcome to the Bitnami elasticsearch container
elasticsearch 17:50:55.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 17:50:55.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 17:50:55.47
elasticsearch 17:50:55.48 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 17:50:55.62 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 17:50:55.75 INFO  ==> Custom configuration file detected, using it...`

**Comment by alvneiayu** [comment]
hi @huzaynbolt 

Sorry I forgot to request you to include inside the docker-compose Elasticsearch section the environment keys:
```
    environment:
      - BITNAMI_DEBUG=true
      - BITNAMI_LOG_LEVEL=trace8
```
Are you including any change inside the scripts? Are you using the original ones? Just to reproduce the issue.

Moreover, what is the way that you fixed the error "Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144"? Are you executing inside the scripts the command "sysctl -w vm.max_map_count=262144"?

Thanks a lot

Álvaro

**Comment by huzaynbolt** [comment]
Hi @alvneiayu , I have added the environment variable, see logs below

I am not modifying the scripts just the environment variables and service name in the docker-compose file .

To fix the Kernel settings issue, I ran the command directly on the Ubuntu box. 


Logs after Docker Compose

mariadb_magento_1  | mariadb 15:52:11.10
mariadb_magento_1  | mariadb 15:52:11.11 Welcome to the Bitnami mariadb container
mariadb_magento_1  | mariadb 15:52:11.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_magento_1  | mariadb 15:52:11.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_magento_1  | mariadb 15:52:11.12
mariadb_magento_1  | mariadb 15:52:11.13 INFO  ==> ** Starting MariaDB setup **
mariadb_magento_1  | mariadb 15:52:11.21 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_magento_1  | mariadb 15:52:11.22 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_magento_1  | mariadb 15:52:11.25 INFO  ==> Initializing mariadb database
mariadb_magento_1  | mariadb 15:52:11.31 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_magento_1  | mariadb 15:52:11.32 INFO  ==> Setting user option
mariadb_magento_1  | mariadb 15:52:11.37 INFO  ==> Using persisted data
mariadb_magento_1  | mariadb 15:52:11.54 INFO  ==> Running mysql_upgrade
mariadb_magento_1  | mariadb 15:52:11.55 INFO  ==> Starting mariadb in background
elasticsearch_1    | elasticsearch 15:52:11.10
elasticsearch_1    | elasticsearch 15:52:11.11 Welcome to the Bitnami elasticsearch container
elasticsearch_1    | elasticsearch 15:52:11.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch_1    | elasticsearch 15:52:11.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch_1    | elasticsearch 15:52:11.12
elasticsearch_1    | elasticsearch 15:52:11.12 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch_1    | elasticsearch 15:52:11.20 DEBUG ==> Validating settings in ELASTICSEARCH_* env vars...
elasticsearch_1    | elasticsearch 15:52:11.24 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch_1    | elasticsearch 15:52:11.27 DEBUG ==> Detected persisted data from previous deployments
elasticsearch_1    | elasticsearch 15:52:11.28 DEBUG ==> Ensuring expected directories/files exist...
elasticsearch_1    | elasticsearch 15:52:11.34 INFO  ==> Setting default configuration
elasticsearch_1    | elasticsearch 15:52:11.44 INFO  ==> Configuring Elasticsearch cluster settings...
elasticsearch_1    | elasticsearch 15:52:11.61 DEBUG ==> Configure Elasticsearch Node type...
magento_1          | magento 15:52:13.78
magento_1          | magento 15:52:13.79 Welcome to the Bitnami magento container
magento_1          | magento 15:52:13.79 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento_1          | magento 15:52:13.80 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento_1          | magento 15:52:13.80
magento_1          | magento 15:52:13.81 INFO  ==> ** Starting Magento setup **
magento_1          | magento 15:52:13.90 DEBUG ==> Validating settings in APACHE_* environment variables
magento_1          | magento 15:52:14.02 INFO  ==> Configuring PHP options
magento_1          | magento 15:52:14.07 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento_1          | magento 15:52:14.17 DEBUG ==> Validating settings in MAGENTO_* environment variables...
elasticsearch_1    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
magento_1          | magento 15:52:14.25 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento_1          | magento 15:52:14.42 INFO  ==> Ensuring Magento directories exist
magento_1          | magento 15:52:14.44 INFO  ==> Configuring permissions
magento_1          | magento 15:52:14.48 INFO  ==> Trying to connect to the database server
magento_1          | magento 15:52:14.50 DEBUG ==> Executing SQL command:
magento_1          | SELECT 1
magento_1          | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb_magento' (115)
mariadb_magento_1  | mariadb 15:52:16.83 INFO  ==> Stopping mariadb
docker_elasticsearch_1 exited with code 1
magento_1          | magento 15:52:21.53 DEBUG ==> Executing SQL command:
magento_1          | SELECT 1
magento_1          | ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb_magento' (115)
mariadb_magento_1  | mariadb 15:52:22.75 INFO  ==> ** MariaDB setup finished! **
mariadb_magento_1  |
mariadb_magento_1  | mariadb 15:52:22.85 INFO  ==> ** Starting MariaDB **
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.29-MariaDB) starting as process 1 ...
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Using Linux native AIO
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Uses event mutexes
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Number of pools: 1
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_magento_1  | 2021-06-28 15:52:22 0 [Note] InnoDB: Waiting for purge to start
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] InnoDB: 10.3.29 started; log sequence number 1625774; transaction id 20
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] InnoDB: Buffer pool(s) load completed at 210628 15:52:23
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Warning] 'proxies_priv' entry '@% root@a6bf19c777ea' ignored in --skip-name-resolve mode.
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] Reading of all Master_info entries succeeded
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] Added new Master_info '' to hash table
mariadb_magento_1  | 2021-06-28 15:52:23 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_magento_1  | Version: '10.3.29-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
magento_1          | magento 15:52:26.55 DEBUG ==> Executing SQL command:
magento_1          | SELECT 1
magento_1          | 1
magento_1          | magento 15:52:26.58 INFO  ==> Trying to connect to Elasticsearch
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution
magento_1          | cannot resolve host "elasticsearch": lookup elasticsearch: Temporary failure in name resolution


Logs in ElasticSearch container

elasticsearch 15:52:11.10
elasticsearch 15:52:11.11 Welcome to the Bitnami elasticsearch container
elasticsearch 15:52:11.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch 15:52:11.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch 15:52:11.12
elasticsearch 15:52:11.12 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 15:52:11.20 DEBUG ==> Validating settings in ELASTICSEARCH_* env vars...
elasticsearch 15:52:11.24 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 15:52:11.27 DEBUG ==> Detected persisted data from previous deployments
elasticsearch 15:52:11.28 DEBUG ==> Ensuring expected directories/files exist...
elasticsearch 15:52:11.34 INFO  ==> Setting default configuration
elasticsearch 15:52:11.44 INFO  ==> Configuring Elasticsearch cluster settings...
elasticsearch 15:52:11.61 DEBUG ==> Configure Elasticsearch Node type...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

**Comment by alvneiayu** [comment]
hi @huzaynbolt 

I tried with this docker-compose (your docker-compose just changing the host):

```
version: '2'
services:
  mariadb_magento:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '8082:8080'
    environment:
      - MAGENTO_HOST=alvaro.nami
      - MAGENTO_DATABASE_HOST=mariadb_magento
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
      - MAGENTO_ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_ELASTICSEARCH_PORT_NUMBER=9200
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb_magento
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:6
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```
And I can not reproduce the problem. I tried several times:

```
docker-compose down -v
docker-compose up
```

and it is working properly:

```
CONTAINER ID   IMAGE                                 COMMAND                   CREATED         STATUS                      PORTS                                                                                                                                  NAMES
b0a8ed704152   bitnami/magento:2                     "/opt/bitnami/script…"    5 minutes ago   Up 5 minutes                8443/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp                                                                                    debian-10_magento_1
0bb352c49615   bitnami/elasticsearch:6               "/opt/bitnami/script…"    5 minutes ago   Up 5 minutes                9200/tcp, 9300/tcp                                                                                                                     debian-10_elasticsearch_1
79015bd53693   bitnami/mariadb:10.3                  "/opt/bitnami/script…"    5 minutes ago   Up 5 minutes                3306/tcp                                                                                                                               debian-10_mariadb_magento_1
```
Is this something that you can reproduce it during the first installation or I need to wait some time (I waited 10 min and I can not see any problem)?

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment]
hi @huzaynbolt
 
you're welcome. Let me know if the problem disappears.

Thanks a lot

Álvaro

**Comment by jvliwanag** [comment]
Also ran into this issue on a 1GB VM. Looks like it's a memory size issue though. I upgraded the VM to 2GB and had to update the virtual memory on the host as well as specified here -- https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html .

This fixed the issue for me.

**Comment by alvneiayu** [comment]
hi @jvliwanag 

Thanks a lot for sharing your solution. @huzaynbolt could you test with this suggestion, please?

Thanks a lot again

Álvaro
