### ISSUE TITLE
Unable to install an Extension Using Composer

### ISSUE THREAD

**Issue by jaaf85** [bitnami/bitnami-docker-magento#199]
Hi,
i am trying to install an extension on magento. But after completing installation process with composer, i am faced to Class Not Found , when i try to access the admin panel of the extension. It seems like composer psr-4 classes for the extension are not listed in the environment. 
importing the extension php classes from vendor directory to generated/code/<Module> resolves the issue . but actually this manual composition is not valid workaround while it has to be performed at each setup:upgrade of magento. 
 
i suspect current state of transition on the stack, while i think i followed the best practices of extension installation listed by bitnami on the several technical docs available.

-------------------------------
    BUG REPORT INFORMATION
-------------------------------
here are key informations from my environment:
--> Host OS : unbuntu 21.04 
--> docker , docker-compose : latest versions at this moment
--> magento community edition
--> extension to install:   Akeneo_connector extension from a platinium partner of magento. "akeneo/module-magento2-connector-community"
--> current magento container key informations: 
approach A with /opt/bitnami/ systempaths,  daemon as the apache user
i am using the default configuration of the image, i just changed the magento host from localhost to fqdn. 

**Description**

1. Access to magento container bash from the host : sudo docker-compose exec magento bash

2. Performing the installation process with daemon user when needed
root @XXXXX:~ composer require akeneo/module-magento2-connector-community
root @XXXXX:~ su daemon -s /bin/bash -c "/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento module:enable Akeneo_Connector"
root @XXXXX:~ su daemon -s /bin/bash -c "/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento setup:upgrade"
root @XXXXX:~ su daemon -s /bin/bash -c "/opt/bitnami/php/bin/php /opt/bitnami/magento/bin/magento cache:flush"
3.  Access the admin page configuration on magento throw exception log message

i also tried an installation with an additional setup:di:compile command, after setup upgrade to recompile , but i face the same problem.

**Describe the results you received:**

 main.CRITICAL: Error: Class 'Akeneo\Connector\Model\Config\Version' not found in /bitnami/magento/generated/code/Akeneo/Connector/Model/Config/Version/Interceptor.php:7
Stack trace:
#0 /bitnami/magento/vendor/composer/ClassLoader.php(444): include()
#1 /bitnami/magento/vendor/composer/ClassLoader.php(322): Composer\Autoload\incl                                                                             udeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFacto                                                                             ry.php(121): spl_autoload_call()
#4 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(                                                                             108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#5 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56)                                                                             : Magento\Framework\ObjectManager\Factory\Compiled->create()
etc....

**Describe the results you expected:**
access to the admin panel UI to configure the extension

**Additional information you deem important (e.g. issue happens only occasionally):**

For information, 
i was foced to install docker and docker-compose with sudo, while it was not possible on the server. 
there is no magento-cli embedded on the docker image , while it seems to be provided on other Bitnami stacks for magento.  so i ddidn't use the magento-cli command, but i used the embedded command su -daemon 
the composer  autoload_psr4.php (in the vendor/composer directory) seems okay while it lists directory matches for akeneo required modules . performing a composer dump_autoload also seems to give a standard result. the only thing i am wondering is about the environment variable VendorDir? maybe there is something weird happenning because of the current instant filecopy between opt/bitnami and bitnami/ ? 

**Version**

- Output of `docker version`:
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:58:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Output of `docker info`:

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-17-generic
 Operating System: Ubuntu 21.04
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.581GiB
 Name: vps-73c654a3
 ID: 7ISF:DTCZ:LYLM:22LP:EGZK:AKCJ:5EUB:GXEF:DH37:TPWS:GDP2:44N6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:58:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
ubuntu@vps-73c654a3:~$ ^C
ubuntu@vps-73c654a3:~$ sudo docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019


**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue

![image](https://user-images.githubusercontent.com/1133777/125584973-bbfa84cf-2c4f-4c38-a354-79152f43cb9e.png)

The only difference I think is that I launched the composer require as the daemon user. I ran setup:di:compile and that generated the classes. Could you also try restarting the container?

**Comment by jaaf85** [comment]
Hi Javsalgar,

Thank you very much for your quick reply ! 
actually you are right, it's working with su-daemon for composer :)!!!. I am happy and confused because i mentionned it as an issue :s
Actually every document on bitnami stack was pointing to use sudo composer or composer directly , and only use the magento/apache user or sudo on magento command ( through magento-cli).  it can be very helpful for others to have this information somewhere for the docker image :)
i past 3 days on this, working on file permission user, and directories for daemon user and not actually thinking of a solution as simple as this :), while i was thinking that composer needs high privileges on files and directories to compose... and the documentation was telling the same .
thanks a lot, you can of course close the issue ! 
 so two more questions related to this: 
 do we always need to use composer with daemon user on btnami magento docker image ? or there is some specific cases ?
Do you have an updated magento-cli script for the new approach A for this docker image  ?  or a su daemon su is sufficient for every case ?

All the best

**Comment by javsalgar** [comment]
Hi! Good to know it's fixed! I think that using daemon should be enough for any case.
