### ISSUE TITLE
Caching until Container restart

### ISSUE THREAD

**Issue by WdaMHamm** [bitnami/bitnami-docker-magento#203]
**Description**

.phtml files are cached until server restart.
Magento 2 Cache Flushing processes/deletion of files does not work.

**Steps to reproduce the issue:**

1. "docker compose up -d" of unchanged docker-compose.yml via Powershell 
2. Upload of module/theme via PHP Storm via mounted network drive to volume
3. Enabling module/theme clearing cache/generating static files
4. Reload webpage on "http://localhost/" to see changes made
5. Change text/html-tags in .phtml file
6. Upload changes
7. Clear cache

**Describe the results you received:**

New changes not displayed after clearing all possible caches + reload.

**Describe the results you expected:**

Changes will display after clearing cache + page reload.

**Additional information you deem important (e.g. issue happens only occasionally):**

Only way of showing changes is restarting magento container (serverrestart)

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 24
  Running: 3
  Paused: 0
  Stopped: 21
 Images: 16
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 25GiB
 Name: docker-desktop
 ID: KEXE:LXG4:UD4U:Y6AX:2LKG:GPF3:UZK4:UIRO:WDQ2:GOQO:6IQI:SXBQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

Docker Desktop on Windows via wsl

Example module
[Test.zip](https://github.com/bitnami/bitnami-docker-magento/files/6891623/Test.zip)

**Comment by hussam-qasem** [comment]
What is your Magento mode set to? e.g.: `docker exec -it magento_magento_1 bash`
then:
```
magento deploy:mode:show
echo $MAGENTO_MODE
```

**Comment by WdaMHamm** [comment]
Currently have it set to 'default' have noticed it first when in 'developer' mode.
Haven't tested it in 'production'.

echo $MAGENTO_MODE doesn't return anything.

**Comment by miguelaeh** [comment]
Hi @WdaMHamm ,
There are a couple of opssible solutions at https://community.magento.com/t5/Magento-2-x-Programming/HTML-changes-do-not-reflect-in-front-end/td-p/466224, could you give them a try?

**Comment by WdaMHamm** [comment]
Heya @miguelaeh,
i think i wasn't clear enought on what exactly i did for cache cleaning so i will list everything i've tried:
(commands are all done in `/bitnami/magento/`)
- clearing browser cache (`Ctrl+Shift+R` and manually clearing browsercache/incognitomode)
- basic cache clearing `bin/magento cache:clean`
- flushing cache `bin/magento cache:flush`
- removing and regenerating files when required as pointed out in https://devdocs.magento.com/guides/v2.4/howdoi/php/php_clear-dirs.html
- using `find` and `grep` to find files in `/opt/bitnami/` and `/bitnami/magento` with my changes and checking if the changes apply in the files (they do)

As i said in my issue the only way to get the desired changes is to restart the magento container.

As there are no mentions of different caching systems form the default magento installation (e.g. varnish, redis, memcached) im not sure where this behaviour is coming from.

**Comment by miguelaeh** [comment]
Hi @WdaMHamm ,
Did you try to disable the cache? Something like:

```
php bin/magento cache:disable block_html
```

**Comment by WdaMHamm** [comment]
Hi @miguelaeh,
i did for all cache types.
Except for a longer load time there was no change.

Can you not reproduce the error on your end following my steps?

**Comment by miguelaeh** [comment]
Hi @WdaMHamm ,
Could you share a link to the module/theme you are using so I can try to reproduce the issue exactly, please?

**Comment by WdaMHamm** [comment]
Hi @miguelaeh

There is the test module at the bottom of my initial post i've used to confirm this problem before posting here.
I have confirmed it not working with different themes and modules from other projects, too.

**Comment by miguelaeh** [comment]
Hi @WdaMHamm ,
I have been trying to install the module you shared but without luck, could you share the exact commands to install it please?
Also, I noticed the `composer.json` in the module you shared is an invalid `json` file, not sure if that could be causing issues.

**Comment by WdaMHamm** [comment]
Heya @miguelaeh,
I just uploaded the module to app/code/.
But i've finally managed to solve the problem. 

Even though the OPCache is given with no defaults it is enabled for the container from the start.

> PHP_ENABLE_OPCACHE: Enable OPcache for PHP scripts. No default. 

Which is bad when trying to develop with phtml files 😅 

I think the readme should mention that the OPCache is enabled by default.

**Comment by miguelaeh** [comment]
Hi @WdaMHamm ,
Thank you very much for sharing the solution!

**Comment by harli91** [comment]
4 days wasted on this :(

**Comment by srokatonie** [comment]
@harli91 Similar here!

**Comment by srokatonie** [comment]
> 4 days wasted on this :(

Same here...

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
