### ISSUE TITLE
Magento installer aborts and container is stopped

### ISSUE THREAD

**Issue by edumicse** [bitnami/bitnami-docker-magento#205]
**Description**

The container is stuck on "Running Magento install script", aborting and stopping the container a few seconds after the container is started.

**Steps to reproduce the issue:**

1. Create docker network magento-network
2. Create and start elastincsearch following https://github.com/bitnami/bitnami-docker-elasticsearch, using network magento-network 
3. Create and start mariadb following https://github.com/bitnami/bitnami-docker-mariadb using network magento-network
4. Create and start magento container following https://github.com/bitnami/bitnami-docker-magent. The issue is reproducible with both docker volumes and mounted host volumes

**Describe the results you received:**

See container log output below:

```console
magento 14:39:51.36
magento 14:39:51.37 Welcome to the Bitnami magento container
magento 14:39:51.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento 14:39:51.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento 14:39:51.37
magento 14:39:51.37 INFO  ==> ** Starting Magento setup **
magento 14:39:51.43 INFO  ==> Configuring PHP options
magento 14:39:51.44 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 14:39:51.48 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
magento 14:39:51.53 INFO  ==> Ensuring Magento directories exist
magento 14:39:51.53 INFO  ==> Configuring permissions
magento 14:39:51.54 INFO  ==> Trying to connect to the database server
magento 14:39:51.56 INFO  ==> Trying to connect to Elasticsearch
magento 14:39:51.56 INFO  ==> Running Magento install script
```

**Describe the results you expected:**

Expecting the installer to complete and the container not to abort

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

Latest magento image

- Output of `docker version`:

```console
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```console
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 8
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: WNHQ:Q6K6:AONC:PIX5:6X6L:33DJ:4SWK:H2S7:ZG56:MPE3:6TVR:GZ7W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```console
Docker Compose version v2.0.0-rc.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running on Docker for Mac

**Comment by juan131** [comment]
Hi @edumicse 

You're creating the containers manually, right? Or are you using a **docker-compose.yml** such as[ the one included on this repository](https://github.com/bitnami/bitnami-docker-magento/blob/master/docker-compose.yml)?

In any case, let's first start by recreating your Magento container adding the environment variable `BITNAMI_DEBUG` that will increase the verbosity of the logs. To do so, you have two options:

- Using the command line: Add the flag `--env BITNAMI_DEBUG=true` to your `docker run` command.
- Using Docker Compose: Modify your **docker-compose.yml** adding the changes below in the environment section:

```diff
version: '2'
services:
  ...
  magento:
    image: docker.io/bitnami/magento:2
    ...
    environment:
+     - BITNAMI_DEBUG=true
      - MAGENTO_HOST=localhost
      ...
```

**Comment by edumicse** [comment]
Hi,

Thank you for the suggestion. Debug printout was very clear. It turned out that the latest MariaDB image is not supported by the latest Magento image: the latest version of MariaDB is 10.5 and the latest Magento image supports 10.2-10.4. So I downgraded MariaDB to 10.4 and could proceed with the installation.

Thank you.
/Eduardas

**Comment by juan131** [comment]
That's great! I'm glad you were able to solve the issue
