### ISSUE TITLE
Static content (js, css etc) not loaded on localhost after installation

### ISSUE THREAD

**Issue by edumicse** [bitnami/bitnami-docker-magento#206]
**Description**
After initial installation is done and the container is restarted, the localhost site is loaded but without any external resources available. All js, css etc are not accessible/loaded, lots of exceptions are logged in the console and the site is unusable. Tried with default localhost and setting a local magento site. Had magento debug enabled while installing. Tried both default and developer modes.

**Steps to reproduce the issue:**

1. Install bitnamin-docker-elasticsearch latest container
2. Install bitnami-docker-mariadb 10.4 container as per description
3. Install bitnami-docker-magento latest container.

Using docker command:
docker run -d --name magento \
  -p 80:80 -p 443:443 -p 8080:8080 -p 8443:8443 \
  --env ALLOW_EMPTY_PASSWORD=yes \
  --env MAGENTO_DATABASE_USER=bn_magento \
  --env MAGENTO_DATABASE_PASSWORD=bitnami \
  --env MAGENTO_DATABASE_NAME=bitnami_magento \
  --env BITNAMI_DEBUG=true \
  --env MAGENTO_HOST=local.magento \
  --env MAGENTO_MODE=developer \
  --env APACHE_HTTP_PORT_NUMBER=8080 \
  --env APACHE_HTTPS_PORT_NUMBER=8443 \
  --env MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=80 \
  --env MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER=443 \
  --network magento-network \
  --volume /Users/eduardas/source/docker-data/magento-data:/bitnami/magento \
  bitnami/magento:latest

**Describe the results you received:**
The tail of the log:

Module 'Vertex_AddressValidation':
[Progress: 1307 / 1314]
Module 'Yotpo_Yotpo':
[Progress: 1308 / 1314]
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1
[Progress: 1309 / 1314]
Installing admin user...
[Progress: 1310 / 1314]
Caches clearing:
Cache cleared successfully
[Progress: 1311 / 1314]
Disabling Maintenance Mode:
[Progress: 1312 / 1314]
Post installation file permissions check...
For security, remove write permissions from these directories: '/opt/bitnami/magento/app/etc'
[Progress: 1313 / 1314]
Write installation date...
[Progress: 1314 / 1314]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
magento 18:49:07.42 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_frontend' to '0'
Value was saved.
magento 18:49:16.33 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_adminhtml' to '0'
Value was saved.
magento 18:49:17.34 DEBUG ==> Setting Magento configuration value 'web/secure/base_url' to 'https://local.magento/'
Value was saved.
magento 18:49:18.32 DEBUG ==> Setting Magento configuration value 'web/unsecure/base_url' to 'http://local.magento/'
Value was saved.
magento 18:49:19.30 DEBUG ==> Setting Magento configuration value 'web/seo/use_rewrites' to '1'
Value was saved.
The following modules have been disabled:
- Magento_TwoFactorAuth

Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:disable' with the --clear-static-content option to clear them.
Enabled developer mode.
magento 18:49:28.50 INFO  ==> Reindexing
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:01
magento 18:49:38.78 INFO  ==> Flushing cache
Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
compiled_config
eav
customer_notification
config_integration
config_integration_api
full_page
config_webservice
translate
vertex
magento 18:49:39.66 INFO  ==> Persisting Magento installation

magento 19:01:58.33 INFO  ==> ** Magento setup finished! **
magento 19:01:58.34 INFO  ==> ** Starting cron **
magento 19:01:58.36 INFO  ==> ** Starting Apache **
[Mon Aug 23 19:01:58.403517 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 23 19:01:58.403894 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 23 19:01:58.435373 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 23 19:01:58.435853 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 23 19:01:58.448885 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Unix) OpenSSL/1.1.1d PHP/7.4.22 configured -- resuming normal operations
[Mon Aug 23 19:01:58.448989 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
172.19.0.1 - - [23/Aug/2021:19:14:01 +0000] "GET / HTTP/1.1" 200 6478
172.19.0.1 - - [23/Aug/2021:19:14:43 +0000] "GET /admin HTTP/1.1" 404 37009
172.19.0.1 - - [23/Aug/2021:19:14:58 +0000] "GET / HTTP/1.1" 200 6490
172.19.0.1 - - [23/Aug/2021:19:15:35 +0000] "-" 408 -

Hitting http://local.magento:8080 will load the doc with lots of missing files. From console:

local.magento/:14 [Report Only] Refused to load the stylesheet 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/mage/calendar.css' because it violates the following Content Security Policy directive: "style-src getfirebug.com cdn.dnky.co webchat.dotdigital.com *.yotpo.com *.googleapis.com 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

local.magento/:15 [Report Only] Refused to load the stylesheet 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/css/styles-m.css' because it violates the following Content Security Policy directive: "style-src getfirebug.com cdn.dnky.co webchat.dotdigital.com *.yotpo.com *.googleapis.com 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

local.magento/:16 [Report Only] Refused to load the stylesheet 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/css/styles-l.css' because it violates the following Content Security Policy directive: "style-src getfirebug.com cdn.dnky.co webchat.dotdigital.com *.yotpo.com *.googleapis.com 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

local.magento/:17 [Report Only] Refused to load the stylesheet 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/css/print.css' because it violates the following Content Security Policy directive: "style-src getfirebug.com cdn.dnky.co webchat.dotdigital.com *.yotpo.com *.googleapis.com 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

5[Report Only] Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src assets.adobedtm.com amcglobal.sc.omtrdc.net dpm.demdex.net cm.everesttech.net widgets.magentocommerce.com data: <URL> <URL> <URL> t.paypal.com *.ftcdn.net *.behance.net <URL> fpdbs.paypal.com fpdbs.sandbox.paypal.com *.vimeocdn.com s.ytimg.com d3sbl0c71oxeok.cloudfront.net dhkkzdfmpzvap.cloudfront.net d2bpzs5y44q6e0.cloudfront.net d37shgu97oizpd.cloudfront.net d1zlqll3enr74n.cloudfront.net d1jynp0fpwn93a.cloudfront.net d2cb3tokgpwh3v.cloudfront.net d1re8bfxx3pw6e.cloudfront.net d35u8xwkxs8vpe.cloudfront.net d13s9xffygp5o.cloudfront.net d388nbw0dwi1jm.cloudfront.net d11p2vtu3dppaw.cloudfront.net d3r89hiip86hka.cloudfront.net dc7snq0c8ipyk.cloudfront.net d5c7kvljggzso.cloudfront.net d2h8yg3ypfzua1.cloudfront.net d1b556x7apj5fb.cloudfront.net draz1ib3z71v2.cloudfront.net dr6hdp4s5yzfc.cloudfront.net d2bomicxw8p7ii.cloudfront.net d3aypcdgvjnnam.cloudfront.net d2a3iuf10348gy.cloudfront.net *.ssl-images-amazon.com *.ssl-images-amazon.co.uk *.ssl-images-amazon.co.jp *.ssl-images-amazon.jp *.ssl-images-amazon.it *.ssl-images-amazon.fr *.ssl-images-amazon.es *.ssl-images-amazon.de *.media-amazon.com *.media-amazon.co.uk *.media-amazon.co.jp *.media-amazon.jp *.media-amazon.it *.media-amazon.fr *.media-amazon.es *.media-amazon.de *.yotpo.com 'self' 'unsafe-inline'".

local.magento/:1 [Report Only] Refused to load the script 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/requirejs/require.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com secure.authorize.net test.authorize.net www.googleadservices.com www.google-analytics.com www.paypalobjects.com js.braintreegateway.com www.paypal.com geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.sandbox.paypal.com t.paypal.com s.ytimg.com video.google.com vimeo.com www.vimeo.com www.youtube.com *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es *.payments-amazon.de *.trackedlink.net *.trackedweb.net *.dotdigital-pages.com cdn.dnky.co api.comapi.com webchat.dotdigital.com *.yotpo.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

local.magento/:23 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/fonts/opensans/light/opensans-300.woff2 net::ERR_EMPTY_RESPONSE
local.magento/:24 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/fonts/opensans/regular/opensans-400.woff2 net::ERR_EMPTY_RESPONSE
local.magento/:27 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/fonts/Luma-Icons.woff2 net::ERR_EMPTY_RESPONSE
local.magento/:26 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/fonts/opensans/bold/opensans-700.woff2 net::ERR_EMPTY_RESPONSE
local.magento/:25 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/fonts/opensans/semibold/opensans-600.woff2 net::ERR_EMPTY_RESPONSE
local.magento/:14 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/mage/calendar.css net::ERR_EMPTY_RESPONSE
local.magento/:22 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/requirejs-config.js net::ERR_EMPTY_RESPONSE
local.magento/:20 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/requirejs/require.js net::ERR_EMPTY_RESPONSE
local.magento/:21 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/mage/requirejs/mixins.js net::ERR_EMPTY_RESPONSE
local.magento/:16 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/css/styles-l.css net::ERR_EMPTY_RESPONSE
local.magento/:15 GET http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/css/styles-m.css net::ERR_EMPTY_RESP

**Describe the results you expected:**

Expected the site to be loaded properly, with external resources loaded and app started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 9
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: WNHQ:Q6K6:AONC:PIX5:6X6L:33DJ:4SWK:H2S7:ZG56:MPE3:6TVR:GZ7W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.0.0-rc.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by yilmi** [comment]
Hi @edumicse,

The issue you're seeing can be cause by more than one configuration (including from the data folder you're mounting) and ideally we'd need a docker-compose repro steps to be able to help.

One example is the use of port 8080 to hit magento from your browser, while the static resources are referenced as http (without port specified, so it tries to connect to port 80)
> Hitting http://local.magento:8080 will load the doc with lots of missing files. From console:
> local.magento/:14 [Report Only] Refused to load the stylesheet 'http://local.magento/static/version1629744544/frontend/Magento/luma/en_US/mage/calendar.css'  <-- Port 80 here

This most likely caused by the following variable you're setting:
> --env MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=80
> --env MAGENTO_EXTERNAL_HTTPS_PORT_NUMBER=443

These two are used to establish magento base URLs:
> magento 18:49:17.34 DEBUG ==> Setting Magento configuration value 'web/secure/base_url' to 'https://local.magento/'
Value was saved.
> magento 18:49:18.32 DEBUG ==> Setting Magento configuration value 'web/unsecure/base_url' to 'http://local.magento/'
Value was saved.

These base_url can be used to rewrite URLs and redirect you to port 80, even if you did hit port 8080 initially.

You could try exposing port 8080 as 80 and port 8443 as 443 (don't expose the container's 80/443 as the process isn't listening to those).

Finally if you can't fix it with this advice, please provide reproduction steps with docker-compose that we could use to help you.

Thanks,
Yass
