### ISSUE TITLE
memory_limit error on first run / install

### ISSUE THREAD

**Issue by borja-celda-lg** [bitnami/bitnami-docker-magento#209]
Hello to everyone, I'm deploying this docker into my computer, but I cannot finish the initial run / setup, it always brings an memory_limit error (php) as you can see in the provided screenshots, I've changed the 768 initial ram limit to about 3Gb, noting else happens, I continue to get the same error, I've checked different docker tags, 2.4.3 2.4.2 2.4.0 2.4.1, different debian variations and nothing else.

I've modified the elasticserch container image because of my M1 processor, the selected one don't work

**Steps to reproduce the issue:**

Follow the TL;DR steps in: https://hub.docker.com/r/bitnami/magento

**Describe the results you received:**

Memory limit error, see screenshot
<img width="1680" alt="Captura de pantalla 2021-09-04 a las 12 00 13" src="https://user-images.githubusercontent.com/81559019/132091022-c124c5a3-b5a0-4802-9e1b-878cad426fba.png">

Also see the my modified docker-compose file
<img width="1680" alt="Captura de pantalla 2021-09-04 a las 12 00 25" src="https://user-images.githubusercontent.com/81559019/132091036-52a8e8b1-8a31-4207-be83-47786482e306.png">

**Describe the results you expected:**

Bootstapping the container and exposing the 80 / 443

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using a M1 powered processor.

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: BRNE:3WRA:A2SW:E33A:DDJW:ETMZ:4JLH:3232:DCZ3:SR5V:ZR2K:7XJQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.0.0-rc.2
```

**Comment by borja-celda-lg** [comment]
Any suggestions?

**Comment by migruiz4** [comment]
Hi @borja-celda-lg,

I'm sorry for the late response. An outage in one of our tools used to keep track of issues made this go unnoticed.

Elasticsearch may be trying to allocate too much memory in your device, could you please try adding the following to your docker-compose?

```diff
  elasticsearch:
    ...
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
```
