### ISSUE TITLE
Magento arm building

### ISSUE THREAD

**Issue by pervitiner** [bitnami/bitnami-docker-magento#211]
**Issue building dockerimage for arm64**

**Steps to reproduce the issue:**
```console
$ git clone git clone https://github.com/bitnami/bitnami-docker-magento.git
$ cd /bitnami-docker-magento/2/debian-10/
$ docker buildx build --platform linux/arm64 --push -t bitnami/magentoarm .
```

**Describe the results you expected:**

I expected to be able to build the arm image with buildx from the Dockerfile

it gives me an error :

```
 => CACHED [16/19] RUN /opt/bitnami/scripts/php/postunpack.sh                                                                                             0.0s
 => ERROR [17/19] RUN /opt/bitnami/scripts/apache-modphp/postunpack.sh                                                                                    0.4s
------                                                                                                                                                         
 > [17/19] RUN /opt/bitnami/scripts/apache-modphp/postunpack.sh:
#21 0.359 /opt/bitnami/scripts/apache-modphp/postunpack.sh: line 20: /opt/bitnami/php/bin/php: No such file or directory
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c /opt/bitnami/scripts/apache-modphp/postunpack.sh" did not complete successfully: exit code: 1
```

**Version**

- Output of `docker version`:

```
Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1
```

**Comment by carrodher** [comment]
Hi, unfortunately, ARM is not a supported architecture at this moment.
We created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
