### ISSUE TITLE
not able to copy and compile our custom code using bitnami/magento 

### ISSUE THREAD

**Issue by 1si11cs122** [bitnami/bitnami-docker-magento#222]
I am using bitnami/magento image to build my custom application.
I tried to copy all my code into container and tried to execute magneto commands. But unfortunately this doesnt work.
Also "WORKDIR  folder" doesnot create folder inside container.
Could you please help me in solving this issue.

**Comment by migruiz4** [comment]
Hi @1si11cs122,

I'm sorry but the information you provided is not enough to help you troubleshoot the issue or determine if it is an issue with the image or not.

Could you please extend this issue with additional information? (error logs, more details about your use case, etc.)

**Comment by 1si11cs122** [comment]
Also i tried to copy into opt/bitnami/magento. It worked well without errors. But after building i am able to see luma shop but not the one which was expected. Also i did docker exec into the container to see if my code was copied.  But i could not see my code anywhere. So even "COPY . ." didnt work. 


FROM bitnami/magento:2.4.2
WORKDIR opt/bitnami/magento
COPY . .
RUN composer require --no-update --dev magento/ece-tools magento/magento-cloud-docker 
RUN composer update
RUN composer install
RUN magento module:status
RUN magento module:enable --all
RUN magento setup:di:compile

**Comment by migruiz4** [comment]
Hi @1si11cs122,

I think it may be an issue with your system permissions and not with the image itself, maybe trying to build with a user that is not the owner of the files.

I performed this quick test:
```bash
git clone https://github.com/magento/ece-tools
git clone https://github.com/magento/magento-cloud-docker

cat << EOF > Dockerfile
FROM bitnami/magento:2.4.2
WORKDIR /test/my_files
COPY . .
WORKDIR /opt/bitnami/magento
EOF

docker build -t test .
docker run --rm test ls -la /test/my_files
```

And the results were:
```console
$ docker run --rm test ls -la /test/my_files
magento 08:05:43.20 
magento 08:05:43.21 Welcome to the Bitnami magento container
magento 08:05:43.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento 08:05:43.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento 08:05:43.21 

total 24
drwxr-xr-x  1 root root 4096 Nov  9 08:05 .
drwxr-xr-x  1 root root 4096 Nov  9 08:00 ..
-rw-r--r--  1 root root  120 Nov  9 08:05 Dockerfile
drwxr-xr-x 12 root root 4096 Nov  9 07:53 ece-tools
drwxr-xr-x 10 root root 4096 Nov  9 07:53 magento-cloud-docker
```

**Comment by 1si11cs122** [comment]
Thank you very much for the response.

do we need to create Dockerfile outside of our application code? i mean from the example above i created Dockerfile inside ece-tools.
I have another question from your code. Do we need to change the working directory to /opt/bitnami/magento to run magento commands or  can we run all the magento commands like setup:upgrade,setup:di:compile  in our own path(/test/my_files).

**Comment by 1si11cs122** [comment]
Hello @migruiz4

The problem is if i run "docker run --rm test ls -la /mycode" i am able to see the folder. But if we pass this image in docker-compose.yml and run yaml file. The containers will be started. If i do "docker exec" on the magento container then i cant see the folder "mycode". Please find the below screenshot for same.

![image](https://user-images.githubusercontent.com/93773017/141053708-63d09d76-f702-4603-9519-d0aac1530452.png)

Now i ran docker-compose and did docker exec 
![image](https://user-images.githubusercontent.com/93773017/141053789-bab1cfe4-b70d-4a7e-9906-8ab1fe7878c3.png)

Below is my docker-compose.yml

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    ports:
      - '3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  
  magento:
    image: ttt:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/opt/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    environment:
      - "discovery.type=single-node"
  
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

**Comment by migruiz4** [comment]
> Now i ran docker-compose and did docker exec 
![image](https://user-images.githubusercontent.com/93773017/141053789-bab1cfe4-b70d-4a7e-9906-8ab1fe7878c3.png)

Please have a look carefully, that in the above image you shared the container `51867d46e19b` is not running your custom image (`ttt`) which contains the code, but instead, it is running the image `bitnami/magento:2` without any customization.

**Comment by 1si11cs122** [comment]
yeah. i realised it now. But why it is not taking my customised image. do you have any idea?

**Comment by migruiz4** [comment]
Use the command `docker-compose down` to remove the containers and services, then run `docker-compose up`. 
https://docs.docker.com/compose/reference/down/

**Comment by 1si11cs122** [comment]
I tried. But still the image is bitnami/magento

**Comment by 1si11cs122** [comment]
strange. But copied entire code to other folder and it worked. Thank you for your support

**Comment by 1si11cs122** [comment]
The code got copied into container. But localhost gives This site can’t be reached

**Comment by migruiz4** [comment]
Hi @1si11cs122,

By running `magento setup:install` you are overriding the container logic and probably misconfiguring it:

https://github.com/bitnami/bitnami-docker-magento/blob/eef0e183f3c9e558312277ef02fd02cfcce285d1/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L169-L203

I would recommend reducing the custom configuration to only the extensions, and configure `setup:install` by using `$MAGENTO_EXTRA_INSTALL_ARGS`.

I'm sorry but helping with customizations further than what we have previously discussed would be out of my scope as issues may not be related to the Magento image itself.

**Comment by 1si11cs122** [comment]
ok..Thank you very much for your support. Just a confirmation do i need to pass these flags(MAGENTO_FIRST_NAME,MAGENTO_LAST_NAME) in  docker-compose as environment variables?

**Comment by migruiz4** [comment]
The environment variables MAGENTO_FIRST_NAME and MAGENTO_LAST_NAME are used to set flags `--admin-firstname` and `--admin-lastname` for the `setup:install` command.

https://github.com/bitnami/bitnami-docker-magento/blob/eef0e183f3c9e558312277ef02fd02cfcce285d1/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L170-L178

They are not mandatory, but if not provided the container will use the default values `FirstName` and `LastName` respectively.
https://github.com/bitnami/bitnami-docker-magento/blob/eef0e183f3c9e558312277ef02fd02cfcce285d1/2/debian-10/rootfs/opt/bitnami/scripts/magento-env.sh#L105-L108
