### ISSUE TITLE
Crashes on start. 

### ISSUE THREAD

**Issue by Tony-The-Developer** [bitnami/bitnami-docker-magento#225]
Hello. I am having an issue with the Helm chart Magento.

I get this error on pod start. All of the other pods are up and running. 
![image](https://user-images.githubusercontent.com/68414482/143537546-50adec35-3449-49eb-8222-5ec6e2b1a4e7.png)

![image](https://user-images.githubusercontent.com/68414482/143537530-8cb03a57-aadb-41b0-948a-00ef1fcf67d9.png)
Please help. Thanks

**Comment by marcosbc** [comment]
Hi @Tony-The-Developer, could you deploy Magento with debug mode? In the Helm chart, it can be done via `image.debug=true`.
