### ISSUE TITLE
Howto: Extend base image with Extensions

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#226]
**Howto: Extend base image with extensions and custom code**

What is the recommended approach to extend the Magento base image and install extensions?

The [steps to install extensions](https://github.com/bitnami/bitnami-docker-magento#installing-magento-extensions) work well for a single container. But I would eventually like to [deploy on Kubernetes using the Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/magento).

`MAGENTO_EXTRA_INSTALL_ARGS` is great to setup [Redis](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html), [RabbitMQ](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/install-rabbitmq.html), [Remote Storage](https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html), etc.

However, I can't figure out the best way to install extensions and my custom code.
1) `MAGENTO_SKIP_BOOTSTRAP` seems interesting, but I don't want to skip it. I just want to run `composer require` afterwards.
2) I noticed the [Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/magento) offers `command` and `args`. But how to use them? and would they be helpful?

Thank you!

**Comment by hussam-qasem** [comment]
Looking at the `rootfs`, it seems I can create my own / user shell scripts and place them in the `/docker-entrypoint-init.d/` directory of the image.

**Comment by rafariossaa** [comment]
Hi, 
  Yes, you could use that. 
  Those scripts are executed [here](https://github.com/bitnami/bitnami-docker-magento/blob/0f42644c91ace390ce1488b8c0783e16f73e77af/2/debian-10/rootfs/opt/bitnami/scripts/magento/entrypoint.sh#L26), after the initial setup is done.

**Comment by hussam-qasem** [comment]
Thank you @rafariossaa. Might be worth mentioning in the [Customize this Image](https://github.com/bitnami/bitnami-docker-magento#customize-this-image) section.

I do have a small concern that I have to do double work after installing the extension by performing:
```
magento setup:upgrade
magento setup:di:compile
magento setup:static-content:deploy -f
magento cache:flush
```
Ideally it would've been nice to have it done all at once somewhere [here](https://github.com/bitnami/bitnami-docker-magento/blob/0f42644c91ace390ce1488b8c0783e16f73e77af/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L251) during initialization.

Running upgrade/compile/deploy slows down the container, and in a [Kubernetes deployment](https://github.com/bitnami/charts/tree/master/bitnami/magento
) sometime causes the probe to restart the container prematurely.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the suggestion. I try to update the README.
  Regarding the point where to do the external initialization, it is very difficult to find a right point where to perform it. It would depend very much on each use case. Maybe you want to build your own image based on ours that make the customization that suit you best. 
  For the kubernetes deployment, maybe you want to consider [enabling](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/values.yaml#L321) the [startup probes.](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)

**Comment by rafariossaa** [comment]
Hi,
  Don't worry, I will close this as soon as the README is updated.
