### ISSUE TITLE
Running cron as non-root

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#228]
**Description**

`bitnami-docker-magento` does not run `cron` as non-root. [README](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80) & [code](https://github.com/bitnami/bitnami-docker-magento/blob/0f42644c91ace390ce1488b8c0783e16f73e77af/2/debian-10/rootfs/opt/bitnami/scripts/magento/run.sh#L36)

**Expected Results**

* What is the best approach to run `cron` as non-root in Magento?
* If I run in Kubernetes with [`replicaCount`](https://github.com/bitnami/charts/tree/master/bitnami/magento) greater than 1, what is the recommend approach to run `cron` in a single pod? Use `StatefulSets` instead of `Deployments` and run on the 1st host?

Thank you!

**Comment by javsalgar** [comment]
Hi 
Please, note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart. This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
