### ISSUE TITLE
Magento Screen not loading CSS and Admin URL is not accessible

### ISSUE THREAD

**Issue by shubhankarbanik95** [bitnami/bitnami-docker-magento#232]
Magento URLs are not accessed properly.

While trying to setup the image using the following command.

docker-compose up -d, 

All three containers (elasticsearch, mariadb, magento) is running in docker desktop.
Then trying to access the magento home page, http://{{localhost_ip}}:{{port}} 

it shows the page , but the page is broken , it seems css/js not loading, Even trying to access the admin page to configure the store , /admin, it shows 404 error.

Can any one help me to investigate the issue here?

Its urgent implementation that I am working on, so would appreciate any help here

**Comment by juan131** [comment]
Hi @shubhankarbanik95 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

**Comment by ngophuong** [comment]
Any update on the issue is highly appreciated ?

**Comment by harli91** [comment]
Any update on the issue is highly appreciated ?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
