### ISSUE TITLE
Php changes not are not reflected on page after cache clear 

### ISSUE THREAD

**Issue by harli91** [bitnami/bitnami-docker-magento#235]
### Name and Version

bitnami/magento:2

### What steps will reproduce the bug?

run docker-compose.yml via docker compose command
install and modify a app/code/module  
 run `setup:upgrade` , `setup:di:compile`  and `cache:clean` 

### What is the expected behavior?

Plugin code should be updated

### What do you see instead?

Plugin code is updated only after i restart the containers

### Additional information

-

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by hussam-qasem** [comment]
I usually do:
```
export HOME=/bitnami/magento
cd
magento module:enable "${MODULE_NAME}"
magento setup:upgrade
magento setup:di:compile
magento setup:static-content:deploy -f
magento indexer:reindex
magento cache:clean
magento cache:flush
```

**Comment by harli91** [comment]
> I usually do:
> 
> ```
> export HOME=/bitnami/magento
> cd
> magento module:enable "${MODULE_NAME}"
> magento setup:upgrade
> magento setup:di:compile
> magento setup:static-content:deploy -f
> magento indexer:reindex
> magento cache:clean
> magento cache:flush
> ```

In my opinion an absurd number, i tried most of them still not working, what user do you use to execute these commands?

**Comment by hussam-qasem** [comment]
Perhaps. This happens to work for me.
I run all my containers as [non-root](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). In this particular case, I use user `1001`

**Comment by harli91** [comment]
is there another cache except for the magento file cache that i need to clear?attempted to run on user 1001 still the same problem

**Comment by harli91** [comment]
see https://github.com/bitnami/bitnami-docker-magento/issues/203
