### ISSUE TITLE
Could not connect with user admin

### ISSUE THREAD

**Issue by nasser-bloopark** [bitnami/bitnami-docker-magento#238]
### Name and Version

bitnami-docker-magento

### What steps will reproduce the bug?

1. After running docker-compose up -d
2. With the provided docker-compose file at https://github.com/bitnami/bitnami-docker-magento/blob/master/docker-compose.yml
3. Magento is installing successfully
4. Then it's not possible to connect with the user admin, we got the error **The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.**

Even when we follow the answers in the magento community like updating user admin or creating new user admin, it's not working, we still got that error

I created a user admin with the following

`./bitnami/magento/bin/magento admin:user:create
`

**Admin user: admin
Admin password: NewP@5sword
Admin email: admin@test.com
Admin first name: Admin
Admin last name: User**

I also updated the default existing admin user password, and unblock him with the unblock command, but still not working, i have the same issue.

### What is the expected behavior?

We should be able to connect as user admin

### What do you see instead?

Instead, we have this error

<img width="1305" alt="Screen Shot 2022-03-14 at 11 25 35 PM" src="https://user-images.githubusercontent.com/67282190/158271049-acdb582c-83b8-435a-a700-5a49495729a0.png">

### Additional information

I'm access Magento with http://localhost and i don't know if the error could be related to the hosts

**Comment by hussam-qasem** [comment]
I'm not certain what you're trying to achieve.
1. The default admin username is `user`
2. The default [`docker-compose.yml`](https://github.com/bitnami/bitnami-docker-magento/blob/43fe7461d604b6b53797a3573f3f32e4cdbea9b8/docker-compose.yml#L26) has `ALLOW_EMPTY_PASSWORD` set to `yes`. So no password in necessary.
3. You can reach the admin console by going to [http://localhost/admin](http://localhost/admin)

If you'd like to start your Magento instance with a pre-defined Admin username and password, I would edit the `docker-compose.yml` and set the following under:
`services` -> `magento` -> `environment`, e.g.:
```YAML
    environment:
      - MAGENTO_USERNAME="admin"
      - MAGENTO_PASSWORD="NewP@5sword"
      - MAGENTO_EMAIL="admin@test.com"
      - MAGENTO_FIRST_NAME="Admin"
      - MAGENTO_LAST_NAME="User"
      # - ALLOW_EMPTY_PASSWORD=yes
```
Look at the [`User and Site configuration`](https://github.com/bitnami/bitnami-docker-magento#user-and-site-configuration) for more details.
