### ISSUE TITLE
server certificate does NOT include an ID which matches the server name

### ISSUE THREAD

**Issue by devphoenix2404** [bitnami/bitnami-docker-magento#241]
### Name and Version

bitnami/magento:2.4.3

### What steps will reproduce the bug?

After all the container up, 
magento container leads to this error 

```[Fri Mar 25 07:17:57.002366 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Fri Mar 25 07:17:57.002873 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Mar 25 07:17:57.042018 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Fri Mar 25 07:17:57.042463 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Mar 25 07:17:57.058695 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Mar 25 07:17:57.058747 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'


Can you please help me to fix this.
Thanks

### What is the expected behavior?

_No response_

### What do you see instead?

No error

### Additional information

_No response_

**Comment by hussam-qasem** [comment]
This is not an error. Just a warning. If you really want, you can change the Server Name directive in the Apache config file.

**Comment by devphoenix2404** [comment]
Thanks, One more question:
When I deploy this image into my dev env it redirect me to localhost and in db also localhost stored.

**Comment by hussam-qasem** [comment]
Correct. Unless you change the ‘MAGENTO_HOST’ env variable. Look at the documentation.

**Comment by javsalgar** [comment]
Hi,

Thank you all for participating! Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
