### ISSUE TITLE
Multistore

### ISSUE THREAD

**Issue by felek000** [bitnami/bitnami-docker-magento#244]
### Name and Version

latest

### What is the problem this feature will solve?

I want to create multi store magento2 installation on local machine

### What is the feature you are proposing to solve the problem?

Add in config ability to add subdomain in store config like sub.mage.local

### What alternatives have you considered?

Instructions how to change config to solve this.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
