### ISSUE TITLE
Username and Password??

### ISSUE THREAD

**Issue by devphoenix2404** [bitnami/bitnami-docker-magento#249]
### Name and Version

bitnami/magento:2.4.3

### What steps will reproduce the bug?

After building image

### What is the expected behavior?

should be login

### What do you see instead?

Hi team, for below command
image is working fine but http://localhost/admin I'm not able to login what is the credentials for this?

Even I've updated the docker-compose file with still its not working

```
      - MAGENTO_USERNAME=adminlocal
      - MAGENTO_PASSWORD=admin@123_
   ```
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

**Comment by hussam-qasem** [comment]
Read the [User and Site Configuration](https://github.com/bitnami/bitnami-docker-magento#user-and-site-configuration) section. Defaults are:
- `MAGENTO_USERNAME`: `user`
- `MAGENTO_PASSWORD`: `bitnami1`

If you'll update your `docker-compose.yaml` file, make sure to start all over again. Assuming you have nothing to loose:
```
docker-compose down -v
docker-compose up -d
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by devphoenix2404** [comment]
Thanks 😊
