### ISSUE TITLE
"GET /favicon.ico HTTP/1.1" 404 41657 while running container

### ISSUE THREAD

**Issue by devphoenix2404** [bitnami/bitnami-docker-magento#250]
### Name and Version

bitnami/magento:2.4.3

### What steps will reproduce the bug?

After building the image

### What do you see instead?

Hi Team,

After successfully building the image, while calling the host I'm getting this error on hostname.

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/53808050/169283237-5ec7e211-36c3-402b-8180-3a6864abca87.png">

Can you please help, where I need to fix it or what I need to check.

Thanks

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by hussam-qasem** [comment]
@devphoenix2404 this has nothing to do with Magento or this Container image. 

Your browser is requesting `favicon.ico` and it’s not available in your web/application server root folder. 

Do a search on “magento favicon”.

**Comment by devphoenix2404** [comment]
@hussam-qasem 

But when I hit `/setup/#/landing-install` I got the response like this

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/53808050/169291308-c76c4209-c1a3-4d1d-889d-7d781dd43bb1.png">

Your browser is requesting favicon.ico and it’s not available in your web/application server root folder.

Do a search on “magento favicon”. ? 

Can you please guide me where in which folder I need to search this?

**Comment by devphoenix2404** [comment]
Guys, Can you please update this issue as it's urgent for me.

**Comment by devphoenix2404** [comment]
any update?

**Comment by hussam-qasem** [comment]
This is the wrong forum for this question. It has nothing to do with the bitnami Magento container. 

As mentioned earlier, do a Google search on “magento favicon”.

**Comment by devphoenix2404** [comment]
@hussam-qasem Okay, but this issue is coming with bitnami/magento image.
