### ISSUE TITLE
magento logs should be pipe out to stdout

### ISSUE THREAD

**Issue by umarizulkifli** [bitnami/bitnami-docker-magento#251]
### Name and Version

bitnami/magento:latest

### What steps will reproduce the bug?

Currently only apache logs being pipe to stdout.
It is useful to have magento logs pipe to stdout to help debug application error

### What is the expected behavior?

magento log files in `/opt/bitnami/magento/var/log` pipe to stdout

### What do you see instead?

only apache logs pipe to stdout
```
root@magento-staging-main-6bc8498d87-c52dh:/opt/bitnami/apache/logs# ls -liat
total 0
 69907704 drwxrwxr-x 1 root root 62 Jan 26 10:09 .
 69907705 lrwxrwxrwx 1 root root 11 Jan 26 10:09 access_log -> /dev/stdout
 69907706 lrwxrwxrwx 1 root root 11 Jan 26 10:09 error_log -> /dev/stderr
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
