### ISSUE TITLE
Stuck at installation

### ISSUE THREAD

**Issue by chubbymomo** [bitnami/bitnami-docker-magento#255]
### Name and Version

bitnami/magneto:latest

### What steps will reproduce the bug?

1. Setup MariaDB (mariadb:latest) in Docker container (Details attached)
[mariadb.txt](https://github.com/bitnami/bitnami-docker-magento/files/9106523/mariadb.txt)
2. Setup Elasticsearch (docker.io/bitnami/elasticsearch:7) as specified by the sample docker-compose.yml (Details attached)
https://github.com/bitnami/bitnami-docker-magento/blob/master/docker-compose.yml
[elasticsearch.txt](https://github.com/bitnami/bitnami-docker-magento/files/9106551/elasticsearch.txt)
3. Setup Magento according to the below docker-compose.yml (Details attached)
[docker-compose.txt](https://github.com/bitnami/bitnami-docker-magento/files/9106547/docker-compose.txt)
[magento.txt](https://github.com/bitnami/bitnami-docker-magento/files/9106563/magento.txt)
[logs.txt](https://github.com/bitnami/bitnami-docker-magento/files/9106568/logs.txt)
4. docker-compose up -d the above docker-compose file

### What is the expected behavior?

I expect for Magento to install, and persist on restart.

### What do you see instead?

It says "Running Magento install script", then the container stops after 10 seconds. Starting the Docker container again, it restarts the installation process.

**Comment by chubbymomo** [comment]
I have done some additional troubleshooting:

Using the "Quick Start" Docker Compose file, I confirmed that I can spin up Magento with no issues. So, I have been taking small steps from the sample Docker Compose file to my own attached above while testing between each change.

I have narrowed down that when I use my preexisting MariaDB container, it has the exact same issue.

I am going to drop and recreate both the database and user, then attempt again.

**Comment by chubbymomo** [comment]
After attempting the default (https://github.com/bitnami/bitnami-docker-magento/blob/master/docker-compose.yml) with both Bitnami's version of MariaDB and the official MariaDB I can confirm that it was the official MariaDB that was causing the issue. I have managed to get past the installation phase using Bitnami's version of MariaDB.

If anyone wants to explain why this is, I would be all ears.

**Comment by hussam-qasem** [comment]
Magento 2.4.x requires MariaDB v10.4. (Or MariaDB v10.3 is also ok for v2.4.3 and older). You’re using MariaDB v10.8 `mariadb:latest`

Read the [Magento System Requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)

To solve your issue, simply tag a compatible  version of MariaDB (eg v10.4)

**Comment by chubbymomo** [comment]
> Magento 2.4.x requires MariaDB v10.4. (Or MariaDB v10.3 is also ok for v2.4.3 and older). You’re using MariaDB v10.8 `mariadb:latest`
> 
> Read the [Magento System Requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
> 
> To solve your issue, simply tag a compatible version of MariaDB (eg v10.4)

Well... Sorry for creating this issue then. Thank you for informing me to this, though I think something to maybe alert the user to this fact could be useful. Other than that, I'm going to close this issue.

Thank you!
