### ISSUE TITLE
cant connect with container in running mode 

### ISSUE THREAD

**Issue by sajidunnar** [bitnami/bitnami-docker-magento#37]
I want to conect with application container to run  some of m2 commands but its not working at all 

I am on windows 10 other contianers work but composer-exec exec dont work but following mostly work 

PS H:\DockerProjects\m2> docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                        NAMES
46f0923f8e2e        bitnami/magento:latest   "/app-entrypoint.sh /"   23 minutes ago      Up 23 minutes       0.0.0.0:9090->80/tcp, 0.0.0.0:455->443/tcp   m2_application_1
d698cd257638        bitnami/mariadb:latest   "/app-entrypoint.sh n"   23 minutes ago      Up 23 minutes       3306/tcp                                     m2_mariadb_1

PS H:\DockerProjects\m2> docker exec -i -t 46f0923f8e2e  sh

**Comment by prydonius** [comment]
Hi @sajidunnar, could you tell us a little bit more about your Docker setup? For example, are you using Docker for Windows or Docker Toolbox? Additionally, the information listed in https://github.com/bitnami/bitnami-docker-magento#issues would be useful.

Thanks!
