### ISSUE TITLE
Can't run php bin/magento setup:upgrade

### ISSUE THREAD

**Issue by caandradeduarte** [bitnami/bitnami-docker-magento#50]
I am trying to use this magento2 docker to develop an extension, but I can't execute the magento cli because even hosting directories as data volumes, the magento directory has no bin folder. 

Is there anyway to use the magento cli with this docker?

**Comment by juan131** [comment]
@caandradeduarte the data volumes only have the data that should be persisted. 
However, you will find the whole Magento structure under `/opt/bitnami/magento/`. The binary is under `/opt/bitnami/magento/htdocs/bin/`. You can check it running:
```
 /opt/bitnami/magento/htdocs/bin/magento -v
```
The data persited under `/bitnami/magento/` are symbolic links from:
 - `/opt/bitnami/magento/htdocs/app/etc/`
 - `/opt/bitnami/magento/htdocs/var/` 
 - `/opt/bitnami/magento/htdocs/pub/media`
 - `/opt/bitnami/magento/htdocs/pub/static`
to the persisted directory.

**Comment by sameersbn** [comment]
@caandradeduarte Closing, please re-open if the issue persists. Thank you for using this image.
