### ISSUE TITLE
System Message: One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by johnjullies** [bitnami/bitnami-docker-magento#60]
I'm new to Magento and I don't know how to setup up the cron job thing. I looked into the [docs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-bkg) and did `crontab -u root -e` but I got:

```
no crontab for root - using an empty one
update-alternatives: error: no alternatives for editor
/usr/bin/sensible-editor: 25: /usr/bin/sensible-editor: editor: not found
/usr/bin/sensible-editor: 28: /usr/bin/sensible-editor: nano: not found
/usr/bin/sensible-editor: 31: /usr/bin/sensible-editor: nano-tiny: not found
/usr/bin/sensible-editor: 34: /usr/bin/sensible-editor: vi: not found
Couldn't find an editor!
Set the $EDITOR environment variable to your desired editor.
crontab: "/usr/bin/sensible-editor" exited with status 1
```

I googled further and found [this](http://magento.stackexchange.com/questions/92737/how-to-fix-one-or-more-indexers-are-invalid-make-sure-your-magento-cron-job-is) but when I typed `bin/magento indexer:reindex` I get a `bash: bin/magento: No such file or directory`.

How do I get the System Message cleared? How do I set up a Magento Cron job?

**Comment by silviofdez** [comment]
In Magento that is the normal behaviour, the cron jobs are already configured and running and you do not need to perform any extra step.

**Comment by johnjullies** [comment]
Why does it say `One or more indexers are invalid. Make sure your Magento cron job is running.` if the cron jobs are already configured and running? Can you explain how is this normal behavior?

**Comment by silviofdez** [comment]
Hi, when you perform a modification then, the indexers change, in that moment the warning message is show. When the cronjob is triggered (once per minute by default) they regenerate the indexers.
