### ISSUE TITLE
PHTML fallback bug

### ISSUE THREAD

**Issue by beerybobb** [bitnami/bitnami-docker-magento#65]
Thanks so much for all your great work on this!

I believe i've found a problem with Magento's fallback theme system when using the volumes.

when a theme is installed using the magento volume, it generally works fine expect when you try to override the base theme's PHTML files. Usually you'd copy this phtml file to your theme's directory and it would use this rather than the base one. However in the Bitnami Magento docker image, the module on the font-end disappears.  

this however works perfectly fine if you move that theme into the /opt/bitnami/magento/app/design.... folders, instead of the volumes.  I've also tested this on other docker images and traditional magento installations using the same theme and they work fine.

i suspect this may have to do with how the image is set up using the /opt/bitnami... and the volumes.

Any advice? thanks!

**Comment by javsalgar** [comment]
Hi, thanks for reporting. Could you please provide exact steps to reproduce the issue? We would like to see this in more detail.

**Comment by beerybobb** [comment]
hi, thanks for getting back so quickly. sure

1. Start a fresh copy of the latest bitnami magento docker image

2. Manually Install any theme such as [snowdog blank](https://github.com/SnowdogApps/magento2-theme-blank-sass) into the Magento volume htdocs/app/design/frontend/[vendor name]/[theme name]/   (composer will automatically add it through the /opt/ directory).

3.  Activate theme. confirm theme is working on the frontend

4. Copy the base magento phtml file you wish to overwrite to your themes directory. for example, copy **/opt/bitnami/magento/htdocs/vendor/magento/module-theme/view/frontend/templates/html/header.phtml**   to your volumes theme directory **/htdocs/app/design/frontend/snowdog/blank/Magento_Theme/templates/html/header/header.phtml**

5. Clear cache if needed & view the front end. the module disappears instead of being called from it's new location

this process works on other images and fresh installations, but they do not have the separate /opt/ directories and volumes, so i suspect it's that.

thanks!

**Comment by Alanf718** [comment]
I'm having this same issue, I spent a long time trying to figure out why it wasn't working, but as soon as I tried another image i didn't run into problems with magento picking up on the templates or modules

**Comment by beerybobb** [comment]
deploying  a project soon and would love to use this image. any ideas?

**Comment by jotadrilo** [comment]
hi, @beerybobb I will try to reproduce this tomorrow morning.

I checked that `app/design` is not being persisted so I will remove all the persistence in the image in order to know if is something specific with the filesystem and how PHP works with `realpath` (I ran into some similar issues with apps using `realpath` against symlinks in the past).

**Comment by jotadrilo** [comment]
hey again!

@beerybobb could you provide detailed steps to reproduce your exact Magento environment?

I'd appreciate if you specify how to install the theme step by step since it could be installed in several ways (via `composer` tool, manually, etc)

**Comment by beerybobb** [comment]
hey @jotadrilo, 

the steps are described [above](https://github.com/bitnami/bitnami-docker-magento/issues/65#issuecomment-302182581). it's a manuall install. If using composer, you have to navigate to the magento directory under /opt/ to have it work. the theme obviously works that way, but editing the theme and transfering files through the /opt/ directory is probably not a good practice.

**Comment by jotadrilo** [comment]
hey!

I tried to install the theme manually but I got problems with the assets compilation steps.

Did you get the theme working just after copying it to the `frontend` path? If you had to compile the assets as well, could you instructions so I can follow them?

I'd also be glad if you share some screenshots of your installation so I know how the theme looks like.

**Comment by beerybobb** [comment]
Hey,

yup, i got it working just after placing it in the folder /app/design/frontend/ . you just have to activate it in the backend after that. there were no compiling steps needed. this methood works on a regular install via something like MAMP or any docker image.

![image](https://cloud.githubusercontent.com/assets/10081140/26792228/bff16c4a-49e7-11e7-90f5-e90911d0ce39.png)

![image](https://cloud.githubusercontent.com/assets/10081140/26792346/1bf9d770-49e8-11e7-8b14-35fa32857413.png)

after placing the theme in the directory, you should see it available in the backend under content -> configuration -> then the default store view
![image](https://cloud.githubusercontent.com/assets/10081140/26792395/4593a5de-49e8-11e7-921e-59a0096ed50c.png)

thanks!

**Comment by javsalgar** [comment]
Hi

I tried following the steps you mentioned but I still get the CSS issues. From the screenshots I see that you are not using the Snowdog theme but one called Rustic Accents. Could you confirm that you can install the Snowdog theme? If so, there must be something I am missing. Thanks.

**Comment by beerybobb** [comment]
With snowdog, you need to compile the sass first. The theme i had was just
renamed RusticAccents

I can install the theme fine but using magentos override/extend of any
phtml causes the module on the frontend to disappear.

So try compiling the css and you should see the theme work.

**Comment by javsalgar** [comment]
Sorry for the late response. We ended up trying the theme Home Design. I installed it without issues, and then did the following:

```
root@4606b6d29f07:/bitnami/magento/htdocs# cp /opt/bitnami/magento/htdocs/vendor/magento/module-theme/view/frontend/templates/html/header.phtml /opt/bitnami/magento/htdocs/vendor/belvg/homedesign/Magento_Theme/templates/html/
```
Then I cleared the cache but saw nothing strange in the UI. What am I supposed to see? Could it be something related to the theme you are using? Could you provide screenshots before and after the change?
