### ISSUE TITLE
How to access Full Code ? 

### ISSUE THREAD

**Issue by sajidunnar** [bitnami/bitnami-docker-magento#75]
My docker composer for Magento is like below
  magento:
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './bitnami:/bitnami'
    depends_on:
      - mariadb

 In bitnami folder I can see apache, Magento and PHP folders but in Magento Folder I can see only app pub and var directories, though fulll code is on this directory /opt/bitnami/magento/htdocs' , if I do following then my container get failed on post installation  ,
    volumes:
      - './bitnami:/bitnami'
      - './htdocs:/opt/bitnami/magento/htdocs'

so question is how I can access whole code so I can do debugging etc with my ide , etc

**Comment by juan131** [comment]
Hi @sajidunnar 

The `/bitnami/magento/` directory only stores the Magento data and configuration files that wants to be persisted (see https://github.com/bitnami/bitnami-docker-magento/blob/master/README.md#persisting-your-application). That data is included in the `/opt/bitnami/magento` using Symbolic Links. Therefore, you can find the data, configuration files and the rest of php files under `/opt/bitnami/magento` but some of them will be pointing to another direction on the file system.

**Comment by sajidunnar** [comment]
@juan131  
Thanks man for prompt reply , I am trying to have persist storage connection like this
- './bitnami:/bitnami'
- './htdocs:/opt/bitnami/magento/htdocs' but it get failed over post installation.

Maybe I am doing something wrong?

**Comment by juan131** [comment]
Hi @sajidunnar I am afraid you cannot persist the whole `/opt/bitnami/magento/htdocs` directory. The nami module which install/configures Magento only allows you to persist the data at `/bitnami/magento/`

Is there any data which is not included at `/bitnami/magento/` that are you worried about to lose?

**Comment by Healkiss** [comment]
I think about package.json and composer.json among other things. But use Symbolic link with magento is not the best solution since it doesn't follow them by default. Some template can't work without symlink activated but it's not recommended on production environments because it represents a potential security risk.

**Comment by tompizmor** [comment]
There is always a tradeoff between security and usability. I am afraid that not using symlinks to persist Magento data means that there is no easy way to update the application. 
Also, it seems that symlinks can be a risk on shared hosts, which it should be the case for containers deploys.

**Comment by intersides** [comment]
If I understand well then there is no way to edit/customize a theme from the mounted volume ?

**Comment by juan131** [comment]
Hi @intersides 

I'm not really sure if I understand your concern. Could you please detail what you're trying to do to edit your themes?

**Comment by intersides** [comment]
Hello @juan131 
I mean to actually edit some scss or javascript files in the default theme (Luma for example) , since they are symlinks that cannot be accessed with an IDE from the mounted volume.

**Comment by juan131** [comment]
Hi @intersides 

They're not symlinks. The mounted volume (found at **/bitnami/magento** inside the container) includes those CSS&JavaScript files themselves. 

The symlinks are at **/opt/bitnami/magento** pointing to the files included on the mounted volume. Therefore, you can edit those files available on the persisted directory with your IDE.

**Comment by intersides** [comment]
Thanks @juan131 
I will give it a try.
