### ISSUE TITLE
Cron jobs failing due to directory permission error

### ISSUE THREAD

**Issue by oranoceallaigh** [bitnami/bitnami-docker-magento#76]
**Description**

A container running off this image (docker image `sha256:e4e889f06666fd18671241ef24e39ba1a391b446814fb4d49200963d4f18512f` at the time of writing) has failing cronjobs, which is triggering an existing Magento 2.2 bug (detailed here https://github.com/magento/magento2/issues/11002)

The failing jobs are ones that use `Session/SaveHandler/Native.php` to try to open a file in `/opt/bitnami/php/tmp` for read/write. The job is running in the context of the `bitnami` user (who is a member of the `daemon` group) but the `/opt/bitnami/php/tmp` directory is owned by `daemon:daemon` with `0755` perms.

**Steps to reproduce the issue:**

1. Run a magento instance as per the instructions in this project's README.
2. Leave for a few minutes so that cron has an opportunity to execute
3. Connect to the mariadb instance and look for `select  * from cron_schedule where status='running';`

**Describe the results you received:**

You should see entries with messages that look like `Warning: SessionHandler::read(): open(/opt/bitnami/php/tmp/sess_jtteejqrk9vbsqufsahtfs51p7, O_RDWR) failed: Permission denied (13) in /opt/bitnami/magento/htdocs/vendor/magento/framework/Session/SaveHandler/Native.php on line 22`

These cron jobs have exited abnormally, triggering the Magento2.2 bug linked to above. Over time the job execution table fills up and the cron job execution consumes more and more system resources.

**Describe the results you expected:**

The Magento bug needs to be fixed upstream. However, the directory permission error is a problem for the Bitnami image itself. A simple `chmod 775 /opt/bitnami/php/tmp` resolves the issue.

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by tompizmor** [comment]
Hi @oranoceallaigh,

Thanks for the super detailed issue. It has been really easy to reproduce the issue.

We will review the Magento permission configuration in order to fix this issue in the container image.

**Comment by tompizmor** [comment]
Hi @oranoceallaigh!

I just wanted to let you know that this issue should have been fixed in the latest Magento release.
