### ISSUE TITLE
Magento 2.2.3 composer update

### ISSUE THREAD

**Issue by Rohaty** [bitnami/bitnami-docker-magento#78]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Rohaty** [comment]
Sorry, wrong inserted text, here is my question:

Hi,
I installed magento version 2.2.3-3.
When I want to run a composer update, it shows me errors:

Can not create cache directory /opt/bitnami/php/composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Update failed (Could not delete /opt/bitnami/apps/magento/htdocs/vendor/symphones/stopwatch/README.md:)

My question is: Do I have to run a composer through sudo and then change the permissions or is there another option? There is another solution like this?
1. sudo /opt/bitnami/php/bin/composer.phar self-update
2. sudo composer update - no-plugins - no-scripts
3.
sudo find / opt / bitnami / apps / magento / htdocs / -type d -exec chmod 755 {} \;
sudo find / opt / bitnami / apps / magento / htdocs / -type f -exec chmod 644 {} \;
sudo chmod + x / opt / bitnami / apps / magento / htdocs / bin / magento-cli
sudo chown -R daemon: daemon / opt / bitnami / apps / magento / htdocs /

What is the correct way to run the composer update in magento 2.2.3-3?

Thank you for the answers.

**Comment by Rohaty** [comment]
I use app Magento 2.2.3-3 on app.bitnamihosting.com

**Comment by carrodher** [comment]
This GitHub issues section is only used to provide support involving application containers, Docker, Kubernetes, etc. Bitnami provides technical support in the [forum](https://community.bitnami.com/). 

We proceed to close this issue.
