### ISSUE TITLE
Invalid cookies path on first run

### ISSUE THREAD

**Issue by mmmcorpsvit** [bitnami/bitnami-docker-magento#87]
lynx localhost

> Accept invalid cookie path=/index.php/ as a prefix of '/'? (n)

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about how to reproduce the issue? Does it happen with Chrome, Firefox? Does it affect the functionality of the application?

**Comment by mmmcorpsvit** [comment]
just run inside docker:
`lynx localhost`

**Comment by marcosbc** [comment]
Hi @mmmcorpsvit,

That message is related to the lynx program. In any case, you can accept cookies by entering "y" when you get that message.
