### ISSUE TITLE
Which Magento is it?

### ISSUE THREAD

**Issue by pitwegner** [bitnami/bitnami-docker-magento#92]
Sorry, this is rather a question than an issue, but which version of Magento is this?
Magento 1 or 2? Commerce or open source? Is this configurable by environment variables?

**Comment by carrodher** [comment]
At the moment I write this comment, the Magento image is `2.2.6` from the 2nd branch of the Open Source project (https://magento.com/tech-resources/download).

You can check the different env variables taking a look at this section of the README:
https://github.com/bitnami/bitnami-docker-magento#environment-variables
