### ISSUE TITLE
How to configure Email settings?

### ISSUE THREAD

**Issue by mtrxreloaded** [bitnami/bitnami-docker-magento#93]
Hi,
This is not a bug. I have installed Bitnami Magento Docker container and it runs fine except that I can't get the mail function to work. I am not able to receive any emails from Magento.

I have configured the "Mail Sending Settings" using an internal smarthost (no authentication required). I am able to use "telnet" to send email within the container. But Magento seems to have problem using that configuration. Please let me know what else need to be configured.

Thank you.

**Comment by mysil2** [comment]
I will suggest to use an extension to ease the setup. Also such extensions often provides a logging function for all sent mail, which is convenient. The one I use is a free Magento 2 SMTP Extension from Mageplaza: https://www.mageplaza.com/magento-2-smtp/

**Comment by juan131** [comment]
Hi @mtrxreloaded 

There are multiple options to send emails from Magento, including solutions based on different plugins. I would recommend going to the [Magento Help Center ](https://support.magento.com/hc/en-us) or [Magento Forums](https://community.magento.com/) for recommendations.
