### ISSUE TITLE
Correct path for themes ? 

### ISSUE THREAD

**Issue by robdcpt** [bitnami/bitnami-docker-magento#98]
Hi,

When the docker magento container is running the 
/opt/bitnami/magento/htdocs/app/design/frontend/Magento
folder is empty. 

Where do I add a new theme on the path ?

**Comment by juan131** [comment]
Hi @robdcpt 

From: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-structure.html

> Storefront themes are conventionally located under app/design/frontend/<Vendor>/. Though technically they can reside in other directories. For example Magento built-in themes can be located under vendor/magento/theme-frontend-<theme_code> when a Magento instance is deployed from the Composer repository.

Magento is deployed with Composer on this Docker image. And, as you can check, themes are under `vendor/magento/`: 

```
$ find /opt/bitnami/magento/ -name themes
/opt/bitnami/magento/htdocs/vendor/magento/module-tinymce-3/view/base/web/tiny_mce/themes
/opt/bitnami/magento/htdocs/vendor/magento/magento2-base/lib/web/jquery/jstree/themes
/opt/bitnami/magento/htdocs/vendor/magento/magento2-base/lib/web/mage/adminhtml/wysiwyg/tiny_mce/themes
/opt/bitnami/magento/htdocs/vendor/magento/magento2-base/lib/web/tiny_mce_4/themes
/opt/bitnami/magento/htdocs/vendor/magento/magento2-base/lib/web/prototype/windows/themes
```

**Comment by robdcpt** [comment]
Thanks Juan. I managed to find them there but when I added my new one under ../vendor/mycompany/mytheme/...  it was picked up even after a cache reload. Are there any additional steps I should take ?

**Comment by andresbono** [comment]
Hi @robdcpt, check if the steps described on this thread work for you:

https://community.magento.com/t5/Installing-Magento-2-x/How-to-install-theme-on-magento-2-for-dummies/m-p/90481/highlight/true#M3788

**Comment by hhdivil** [comment]
What's the correct way to add a custom theme?

**Comment by juan131** [comment]
Hi @hhdivil 

Did you check the link @andresbono shared on the previous comment?
