### ISSUE TITLE
Recommended way to run this violates the recommended way to run bitnami mariadb

### ISSUE THREAD

**Issue by Braintelligence** [bitnami/bitnami-docker-magento#99]
As per https://github.com/bitnami/bitnami-docker-mariadb#allowing-empty-passwords which says `This env variable is only recommended for testing or development purposes.` I don't understand why the readme says that running this env variable is the **recommended** way to run this docker app.

Please explain this contradiction; why is it alright for this repo to use this setting in production whereas it's not alright to do this for the underlying mariadb image in its own repo?

**Comment by andresbono** [comment]
Hi @Braintelligence, just answered in the PR that you mentioned: https://github.com/bitnami/bitnami-docker-magento/pull/54.

> Hi @Braintelligence, Note that not setting a root password for the database shouldn't be an issue because the database port is not exposed (check the docker-compose.yml).
> 
> When you launch the MariaDB container or docker-compose you should expose the port to access the database but that's a different scenario.
>
> In any case, we will check the rationale of this change, if it still is necessary (it was some time ago) and we'll get back to you.

**Comment by andresbono** [comment]
Hi @Braintelligence, after checking it, setting a well-known default password (it would be written in all the docker-compose files in all our containers) for the database root user isn't more secure that not setting it at all.

This way, the user is forced to choose a password for the root user and that one would be unique and secret.

**Comment by andresbono** [comment]
That is not exactly what I meant: Allowing connections with a default password that everybody knows is not safer than allowing connections without password. That's the main idea.

**Comment by Braintelligence** [comment]
Why do you assume that other docker containers that might be in the same network due to human error can read other docker compose yml on the host?

**Comment by tompizmor** [comment]
@Braintelligence I think @andresbono refers something else. He says that use no password at all in the default docker-compose file, or use a well-known password by default (for example `bitnami1234`) has the same level of security because the password is publicly available. 

In any case, the docker-compose files in bitnami repositories are not recommended for production, they are meant to be used for development or testing. For production environments you can see the [helm chart](https://github.com/helm/charts/blob/master/stable/magento/templates/_helpers.tpl#L18-L24) configuration where a random password is always generated unless you specify one

**Comment by andresbono** [comment]
The usage of docker-compose itself is what makes it recommended for testing or development only. What would happen if the containers stop? The services will go unavailable. Using Kubernetes to orchestrate the deployment is what we recommend for production.

**Comment by Braintelligence** [comment]
Mailcow-dockerized is a project that is extremely widely used in production and not only is it based on docker-compose but it's also not compatible with orchestration in its current form.

Your remark that docker-compose is not viable for production defies reality. Not everyone needs orchestration for productive use.

Other than that, not having set restart: always for example is an entirely different problem than contradicting security-implicative recommendations from the same repo group.

I understand the mindset and focus of said group a lot better now, though. Thanks for clearing up your standpoint on production viable tools. I'll stick to a project that is deployment-agnostic in its security concerns and recommendations.
